### PR TITLE
nasa-ghg and nasa-veda: Use an init container to populate example notebooks

### PR DESCRIPTION
**Pull request by sunu**
We use [jupyterhub-gitpuller-init](https://github.com/NASA-IMPACT/jupyterhub-gitpuller-init) to clone the example notebooks into the user's workspace for nasa-veda and nasa-ghg hubs.

Addresses https://github.com/NASA-IMPACT/veda-jupyterhub/issues/28 and https://github.com/NASA-IMPACT/veda-jupyterhub/issues/18

cc @batpad

### CODE REVIEW

**Comment by batpad** [comment]
@sunu this looks good to me! Can you confirm that you've tested this on your testing JupyterHub setup and that it all seems to work fine?

@yuvipanda @consideRatio what would be the best way to test this? Is there a good way to just deploy to staging or test, or should we just deploy and just coordinate timings to fix things in case anything comes up? Thank you!

**Comment by sunu** [comment]
> @sunu this looks good to me! Can you confirm that you've tested this on your testing JupyterHub setup and that it all seems to work fine?

Yes, I tested on a Jupyterhub instance and the init container clones the specified git repository successfully.

**Comment by yuvipanda** [comment]
Eventually we'll have to find a way to let you do that yourselves in a limited way (#3962). But in the meantime, I've deployed this to both the GHG and VEDA staging hubs!

**Comment by batpad** [comment]
I tested this on both the VEDA and GHG staging hubs and it seems to work as expected! 🙏

**Pull request merged**
