### PR TITLE
Split EFS lifecycle into two blocks

### PR DESCRIPTION
**Pull request by yuvipanda**
Otherwise it succeeds on plan but fails on apply

https://github.com/hashicorp/terraform-provider-aws/issues/21862#issuecomment-1007115545

Follow-up to https://github.com/2i2c-org/infrastructure/pull/3183

### CODE REVIEW

**Comment by yuvipanda** [comment]
terraform apply works with this now

**Comment by yuvipanda** [comment]
image

**Comment by yuvipanda** [comment]
Self-merging as a syntactic fixup

**Review by GeorgianaElena — APPROVED** [review]
🚀

**Pull request merged**
