### PR TITLE
nasa-veda: Provide access to a few more buckets

### PR DESCRIPTION
**Pull request by ranchodeluxe**
Provide access to a few more buckets

Ref: https://2i2c.freshdesk.com/support/tickets/759

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks @ranchodeluxe - this looks ok to me. However, my concern usually is that sometimes there's a tf state bucket in the same AWS account that this might give access to if it is not secured specifically. Can I just get an explicit check to make sure this isn't the case? Happy to merge and deploy after that.

**Comment by ranchodeluxe** [comment]
> Thanks @ranchodeluxe - this looks ok to me. However, my concern usually is that sometimes there's a tf state bucket in the same AWS account that this might give access to if it is not secured specifically. Can I just get an explicit check to make sure this isn't the case? Happy to merge and deploy after that.

Yep, not the case so we are good

**Comment by yuvipanda** [comment]
Thanks @ranchodeluxe!

**Comment by yuvipanda** [comment]
@ranchodeluxe applied! LMK if it works ok

**Pull request merged**
