### PR TITLE
Fix typo in deployer start-docker-proxy

### PR DESCRIPTION
**Pull request by pnasrat**

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
LGTM.

I would suggest merging and aborting the deploy and test hubs workflow just after is created to not run another healthcheck and start servers etc for this.

a practice discussed in https://github.com/2i2c-org/infrastructure/issues/2009

**Comment by pnasrat** [comment]
@consideRatio I don't see consensus the issue linked that is an adopted policy.

**Comment by consideRatio** [comment]
@pnasrat the cancelled workflow was the workflow responsible for commenting on this PR that a CD has started I think, while its actually ended up making a full re-deploy in https://github.com/2i2c-org/infrastructure/actions/runs/4305541369.

Feel free to ignore the failure in utoronto staging, I'm working to figure that out already!

**Comment by pnasrat** [comment]
Ugh that was unobvious to me, I guess I thought it was just the early stage of the deploy and cancelling would not trigger any further actions

**Pull request merged**
