### PR TITLE
Add deployer command to open a shell with user homedirs

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/2i2c-org/infrastructure/issues/1225

Example:

```
❯ python3 deployer exec-homes-shell 2i2c staging                                                                                      2 ↵
Activated service account credentials for: [pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com]
Fetching cluster endpoint and auth data.
kubeconfig entry generated for pilot-hubs-cluster.
If you don't see a command prompt, try pressing enter.
root@shell:/# 
root@shell:/# cd home
root@shell:/home# ls
0000-2d0002-2d8055-2d2870  damianavila-402i2c-2eorg           georgianaelena                              yuvipanda-402i2c-2eorg
_shared                    deployment-2dservice-2dcheck       georgianaelena-402i2c-2eorg                 yuvipanda-40gmail-2ecom
blablabla                  dolocansimona-40gmail-2ecom        oauth2-7corcid-7c0000-2d0002-2d8055-2d2870
choldgraf-40gmail-2ecom    georgiana-2edolocan-40gmail-2ecom  sgibson-402i2c-2eorg
root@shell:/home# 
```

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
Love it! ✨ This could also be used when decommissioning a hub and deleting user's home dirs (I plan to test it with `anu` 😅 )

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, great use case! To ensure we don't accidentally delete the wrong hub homes, I've added the name of the hub to the pod name. This puts the name of the hub in the default prompt, so it looks like:

```
root@staging-shell:/#
```

**Comment by GeorgianaElena** [comment]
Amazing <3 LGTM 🚀

**Comment by sgibson91** [comment]
> puts the name of the hub in the default prompt

Can we add this magic so the name of the cluster is added to the prompt for use-cluster-credentials? :D I think there's an in-line TODO comment but I didn't know how to do it

**Comment by yuvipanda** [comment]
@sgibson91 oh yeah i can take that on!

**Comment by yuvipanda** [comment]
@sgibson91 so i poked at this and as you mentioned it's difficult because if we pass `-l` to shells, they set `PS1` and override ours. 

How about using something like https://github.com/jonmosco/kube-ps1 or (what I use) https://starship.rs/. This lets us put the current active kubectl context. Mine looks like this:

image

I think that might be the way to go, not PS1 :( 

If we want to use PS1, we should have have `use-cluster-config` print `PS1=<PS1>`, and then execute it as `source $(<use-cluster-config command)` - this is how `minikube` sets env vars.

**Comment by sgibson91** [comment]
I use oh-my-zsh which does this as well. I guess we're just relying on everyone having some kind of terminal setup that shows this kind of context and remembering to exit the shell created after running use-cluster-credentials.

**Comment by yuvipanda** [comment]
@sgibson91 yeah :(

**Comment by sgibson91** [comment]
Can we get the next shell to print a message before handing over the prompt? Something like "Hello, you are now using CLUSTER's credentials! You can make kubectl calls against this cluster as normal. Remember to exit it once you're done!"

I'm thinking similar to how the terminal app prints "Last login:" before I get my prompt

**Comment by damianavila** [comment]
Lovely stuff, @yuvipanda. Thanks!!

**Pull request merged**
