### PR TITLE
Enable pre-puller for climatematch image

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://climatematch.2i2c.cloud/services/configurator/

Should make startups faster

### CODE REVIEW

**Comment by yuvipanda** [comment]
Gotta wait to hear back from them.

**Review by consideRatio — COMMENTED** [review]
If they dont have a dedicated node pool, pre-pulling is likely going to slow down startup of other users starting up on a node.

Kubelet pulls images in sequence and two separate pods needing images can end up block pulling for another pods.

Due to this, i think prepulling in a shared cluster must come with a major disclaimer of needing a dedicated node pool to not slow things down for all other hubs when a user pod is scheduled ona new node.

**Comment by yuvipanda** [comment]
I've added a note about this being a dedicated nodepool as well.

**Comment by yuvipanda** [comment]
(self merging as an image setup!)

**Pull request merged**
