### PR TITLE
Offer support for enabling NFS protocol for azure storage

### PR DESCRIPTION
**Pull request by GeorgianaElena**

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]
Looks good to me! Thank you for pulling this together so quickly!

**Comment by yuvipanda** [comment]
To use this, you've to enable the hub to use NFS as well - with config like https://github.com/2i2c-org/infrastructure/blob/095a4e80e8255eba9abd8600b38cc6029a7379ce/config/hubs/carbonplan.cluster.yaml#L40. Need to turn AzureFile mounting off here: https://github.com/2i2c-org/infrastructure/blob/095a4e80e8255eba9abd8600b38cc6029a7379ce/config/hubs/utoronto.cluster.yaml#L32

**Comment by GeorgianaElena** [comment]
@yuvipanda, is it ok if we go with basehub template defaults?
i.e., AzureFile disabled and nfs with this config:
https://github.com/2i2c-org/infrastructure/blob/095a4e80e8255eba9abd8600b38cc6029a7379ce/hub-templates/basehub/values.yaml#L14-L26

Thank you!!

**Comment by yuvipanda** [comment]
@GeorgianaElena you'll need to specify the URL still, otherwise the base setup might be ok.

**Comment by GeorgianaElena** [comment]
@yuvipanda, I think I'm a bit confused and would really appreciate some guidance.

1. "the URL" means `serverIP`, right? But how do I know the address of the nfs server if there isn't any right now?
2. what happens with the `home-azurefile` volume when I deploy these changes? Do I need to manually clean it up?

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, so I think you've to terraform apply to get the server IP, and then add that into the config. Given there are no users on this, I think you should just apply it - the config looks ok to me. 

For (2), helm should clean that up.

**Comment by GeorgianaElena** [comment]
Perfect! Thanks a lot @yuvipanda!

**Comment by sgibson91** [comment]
@GeorgianaElena You can ask Terraform to output the URL of the Fileshare: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share#attributes-reference

**Review by sgibson91 — APPROVED** [review]
LGTM! Thank you bearing with me in Slack! 🌺 Feel free to run tf apply and then merge this

**Comment by GeorgianaElena** [comment]
Applied :rocket: 

Thanks for bearing with me too :sparkling_heart:

**Pull request merged**
