### PR TITLE
Init `comment_id` in comment plan workflow

### PR DESCRIPTION
**Pull request by GeorgianaElena**
I believe an empty `issue_comments` might be what's causing the undefined `comment_id` issues?

Ref: https://github.com/2i2c-org/infrastructure/pull/1701

### CODE REVIEW

**Comment by sgibson91** [comment]
I'll come back to this, but I'm not wholly convinced that predefining `comment_id` should be required given that we are using `next`. I understood it that it would use the default arg provided (second arg) if the first arg didn't return anything (and I believe that this understanding is consistent with how we use `next` in other parts of the codebase). And hence I believe there's something a little more sinister going on with `ghapi` in the loop that I'd like to investigate as well.

**Comment by sgibson91** [comment]
https://docs.python.org/3/library/functions.html#next

**Comment by GeorgianaElena** [comment]
Totally agree about the `next` functionality thing. But that's under a `for` statement:
```for page in issue_comments:```, and if `issue_comments` is None, than the `next` isn't  even called I beleive.

**Comment by GeorgianaElena** [comment]
Sorry if I'm not making any sense btw. Wished we were in front of the same screen and debug this together ✨

**Comment by sgibson91** [comment]
Yeah, I need to verify my beliefs of what `issue_comments` returns. For example, I believe that if an issue exists, then the top comment is also treated as an issue comment, so then `len(issue_comments) == 1` always and that singular item is a dict of metadata about the issue top comment. That is either not the case, or something else is going wrong meaning we get something that breaks the code saved to `issue_comments` instead.

**Comment by sgibson91** [comment]
What you're saying makes sense, but I expect it's something sinister that is causing this issue that I want to investigate a little bit more and decide that this is indeed the correct fix.

I also think I'll strip out ghapi.

**Comment by GeorgianaElena** [comment]
> I also think I'll strip out ghapi.

👍🏼 Let's close this then.

**Comment by sgibson91** [comment]
So this workflow worked here: https://github.com/2i2c-org/infrastructure/pull/1727#issuecomment-1255529787 and it has multiple comments beforehand.

Hence I think the below statement is False.

> I believe that if an issue exists, then the top comment is also treated as an issue comment, so then `len(issue_comments) == 1` always and that singular item is a dict of metadata about the issue top comment.

And instead this statement is True.

> if `issue_comments` is None, than the `next` isn't even called I beleive.

Hence I believe we should reopen this PR and merge :)

Sorry for taking you around the houses @GeorgianaElena!!

**Comment by GeorgianaElena** [comment]
No worries @sgibson91 and thanks for thinking about it still

**Review by sgibson91 — APPROVED** [review]

**Review by damianavila — APPROVED** [review]

**Pull request merged**
