### PR TITLE
Add debug helper scripts, make into a minimal package & use typer

### PR DESCRIPTION
**Pull request by yuvipanda**
This PR ended up being a bit longer than I had hoped, but I can't think of easy ways to disentangle this! Here's the three things that are happening here.

# 1. New scripts useful for debugging

While helping debug the last UToronto incident, I realized I've a bunch of useful aliases (https://github.com/yuvipanda/dotfiles/blob/master/aliases) focused on debugging JupyterHub issues that might be helpful for others too. Instead of fiddling with shell, I instead wrote a `debug.py` that can be invoked from the commandline similar to `exec-homes-shell`!

Want to look at the logs of the JupyterHub pod in the prod hub in the UToronto cluster? You can now with:

```
python3 -m deployer.debug component-logs utoronto prod hub
```

This command takes care of authenticating appropriately, and figuring out the correct kubectl commands to make this work. You can also look at the proxy logs with:

```
python3 -m deployer.debug component-logs utoronto prod proxy
```

or the dask-gateway controller logs with

```
python3 -m deployer.debug component-logs 2i2c dask-staging dask-gateway-controller
```

See `python3 -m deployer.debug component-logs --help` for more information.

In addition to looking at component-logs, I've added the following subcommands:

1. `user-logs` to look at logs from the user pod, given a particular username. It takes care of appropriate escaping for you as well, so you can give it the username the user sees without having to do any replacements.
2. `exec-hub-shell` gives you a shell in the hub pod itself, so you can poke around. Particularly helpful to poke around the sqlite db itself, or, uh, to delete logs if they're too big
3. `exec-homes-shell` is same as the old `exec-homes-shell`, which was under deployer. I think this is a better fit, so it's here now.

# 2. [typer](https://typer.tiangolo.com/) for CLI management

As I was trying to add these extra commands, the duplication when using `argparse` got a little frustrating to me. Adding a new command required we write a bunch of boilerplate, and duplicate help strings in multiple places. I looked around with ways to fix it, and found [typer](https://typer.tiangolo.com/) from the same nice people who made FastAPI.
It leverages type hints (present since python 3.6) to minimize amount of boilerplate needed for making new subcommands, and I *immensely* like it! It is what [click](https://click.palletsprojects.com/en/8.1.x/) could have been if click was built post Python 3.6. typer is built alongside FastAPI and uses an extremely similar API, so I'm confident it'll survive long term. 

I've also moved the existing commandline parsing code to using typer, and I think overall it is clearer because of this. There's less duplication, and adding new commands is easier as well. Should also help with https://github.com/2i2c-org/infrastructure/issues/1472

# 3. Making the deployer into a package https://github.com/2i2c-org/infrastructure/issues/970

While setting up the added script, I ran into a lot of difficulty with relative imports (or the lack thereof). The simplest way to fix this was to make it a 'real' module, so I did the *simplest* thing possible to do so:

1. Add a super simple `setup.py` file
2. Make all imports be relative
3. Add console scripts for `deployer`, so it can be simply called as `deployer` rather than as `python deployer`

Again, the primary goal here was to make sure that relative imports work fine, rather than anything to do with actually packaging this for use.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@sgibson91 I know you might also have to fiddle with these scripts and CI when debugging https://github.com/2i2c-org/infrastructure/issues/1862 and friends. Am happy to rebase this after that is done (if needed)

**Comment by choldgraf** [comment]
fun fact, it seems like Type actually [uses Click under the hood](https://typer.tiangolo.com/alternatives/#click)

**Comment by sgibson91** [comment]
> debugging #1862 and friends. Am happy to rebase this after that is done (if needed)

I actually think the conflict will be with #1870 

I never successfully got onboard with writing cli's with click or similar because I conceptually struggle with the decorator aspect and... yeah, it just never worked for my mental model. This was a few years ago though, so maybe typer is easier than I found click, or click is easier than it was then. Who knows! Either way, I'll give the job of providing an official review to someone on the team with the conceptual know-how.

A couple of general things...

1. I LOVE LOVE **_LOVE_** that we are moving towards the deployer being standalone! Thank you also for updating all of the documentation and GHA related stuff with the change to the invocation.
2. **Requested change.** I appreciate the minimal `setup.py`, but the files under the `shared` directory need to be ingested too. The deployer depends on those files and the whole folder would move if we were to extract the deployer to it's own repo, so we need to ensure they're included in the packaging too. I think JupyterHub does something like this:
   - https://github.com/jupyterhub/jupyterhub/blob/main/setup.py#L27
   - https://github.com/jupyterhub/jupyterhub/tree/main/share/jupyterhub
3. **For a follow-up PR.** Can we agree on a cli standard for commands/subcommands, _any_ standard, and document it somewhere? We will now have `deployer <command>`, `deployer.debug <command>` and then there's the by itself `deployer/update_central_grafana_datasources.py`, and it keeps me up at night 😅 In terms of documentation location, I think we could put this standard in `deployer/README.md` for now, but I could imagine it moving into a `CONTRIBUTING.md` if/when we split the deployer out into its own repo.

**Comment by yuvipanda** [comment]
Thank you very much for your comment, @sgibson91! Here's a couple things I've done:

1. I've gotten rid of the separate `deployer.debug` command, and put everything just back under `deployer`. So we still have one command (`deployer`) with a bunch of subcommands, same as before. It might make sense to split that out into multiple commands in the future, but this simplifies the setup for now so we don't have to write any guidelines for what goes where :D 
2. Instead of the pattern from jupyterhub (and its `share/` directory), I've instead used the pattern from `repo2docker` instead, which puts the files the package needs inside the package itself. So I've moved the *one* file that is needed for the package to function (the json schema), and made sure to include it via `MANIFEST.in`. This turned out to be the pattern we were already using, as we are already including files there we need (the tests and the test notebooks!). This won't work outside this repo yet (as I think there are probably other things that need doing), but I don't personally want to work on that part quite yet - just wanted to do the least possible to get this working, and make sure I'm not doing any antipatterns.
3. I appreciate the concern around click, and for what it's worth I could never wrap my head around click either. I tried again this time, and came to the same conclusion as before - I just couldn't really figure out how to use click. I was going to go back to argparse before I found typer, and I definitely found it much more intuitive to use than I ever did click. I'm very happy to put in whatever time (or changes) required to make sure you feel comfortable working on the codebase! Please let me know (here, or in private) and I'll prioritize that. It also has default rich integration which I quite like (see the new command help output in the README, much nicer!)

I'm going to debug these test failures now to see what is up.

**Comment by yuvipanda** [comment]
Tests fixed, ready to go!

**Review by sgibson91 — APPROVED** [review]
Let's get this merged before anything else underneath changes :)

**Comment by yuvipanda** [comment]
Yay thanks @sgibson91!

**Pull request merged**
