### PR TITLE
Add initial config for Temple university

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/2i2c-org/infrastructure/issues/1648

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
🚀

**Comment by GeorgianaElena** [comment]
Hmm, for some reason I don't see myself as an admin on this hub. Wondering what's that about

**Comment by GeorgianaElena** [comment]
@yuvipanda, I opened https://github.com/2i2c-org/infrastructure/issues/1671 since I think it might be a real, more general issue. But I couldn't find a fix to it today though :(

**Comment by yuvipanda** [comment]
@GeorgianaElena I think the issue seems to have fixed itself somehow? I'm definitely not seeing it anymore :)

**Comment by GeorgianaElena** [comment]
Yes, I noticed it too. Damian has been added too on the other hubs that I've deleted him from, so somehow this resolved itself? I'm really confused about what happened 😅 Will close the specific issue too and hopefully it doesn't resurface again.

**Comment by sgibson91** [comment]
I did merge a PR yesterday that forced a deploy across all hubs. While that explains why people who are missing are back, it doesn't explain why they were missing in the first place.

**Comment by damianavila** [comment]
> And somehow, now he was,

I am a mystery... 😜

**Pull request merged**
