### PR TITLE
CSU  hub: set user_name pattern to only edu

### PR DESCRIPTION
**Pull request by sean-morris**
This is intended to serve CSU's; I changed the username pattern to include any edu.

### CODE REVIEW

**Review by GeorgianaElena — CHANGES_REQUESTED** [review]
@sean-morris, I believe that right now this is the only hub left that works with username & password authentication through `auth0`. Is this something that's still wanted?

If not, I believe in addition to only allow `.edu` addresses maybe we can also switch this hub to CILogon so that institutionals identity providers can be used too (example PR that does the same thing https://github.com/2i2c-org/infrastructure/pull/1218)

For context, the `cloudbank demo` hub used to have the same config and we changed it to cilogon + `.edu` allow list because of https://github.com/2i2c-org/infrastructure/issues/1216.

**Comment by sean-morris** [comment]
> @sean-morris, I believe that right now this is the only hub left that works with username & password authentication through `auth0`. Is this something that's still wanted?
> 
> If not, I believe in addition to only allow `.edu` addresses maybe we can also switch this hub to CILogon so that institutionals identity providers can be used too (example PR that does the same thing #1218)
> 
> For context, the `cloudbank demo` hub used to have the same config and we changed it to cilogon + `.edu` allow list because of #1216.

perfect yes. I am with you. It should be correct for cilogon now. Thanks

**Review by yuvipanda — APPROVED** [review]
Try it out!

**Comment by sean-morris** [comment]
> Try it out!

Thanks!

**Pull request merged**
