### PR TITLE
Enable named servers for m2lines & pangeo-hubs

### PR DESCRIPTION
**Pull request by yuvipanda**
I think we should enable this for all research hubs.

Based on request by @dhruvbalwada

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]

**Review by sgibson91 — APPROVED** [review]

**Comment by dhruvbalwada** [comment]
Thank you for this. I am unsure how to use this feature, should i be seeing an option when I login?

**Comment by dhruvbalwada** [comment]
Found it. I can access additional servers through the hub control panel.

**Comment by dhruvbalwada** [comment]
However, when I try it i get an error: 
Screen Shot 2022-12-15 at 2 50 06 PM

**Comment by dhruvbalwada** [comment]
Thank you for this.

**Pull request merged**
