### PR TITLE
AWI-CIROH, prod: added r kernel in options

### PR DESCRIPTION
**Pull request by sepehrkrz**
Added an option in profile listings for the R kernel image

### CODE REVIEW

**Comment by sgibson91** [comment]
Hi @sepehrkrz will using be using RStudio with this new image? If yes, we need to make some extra config tweaks.

**Comment by sepehrkrz** [comment]
Hi @sgibson91! For now we just want use the R kernel. Thank you

**Comment by benlee0423** [comment]
@sgibson91 Can you advise what config changes needed from our side? Does it has to happen in image repo or this repo?

**Comment by sgibson91** [comment]
@benlee0423 if you're not using RStudio, no config changes are required. But they would need to happen on this repo. I'll merge this PR as is when I'm at my computer.

**Pull request merged**
