### PR TITLE
cryo: Allow GPU nodes to spawn across AZs

### PR DESCRIPTION
**Pull request by yuvipanda**
We already do this for GCP, now we do it on AWS too.

Fixes https://github.com/2i2c-org/infrastructure/issues/3334

### CODE REVIEW

**Comment by yuvipanda** [comment]
Deployed and tested on cryo

**Review by GeorgianaElena — APPROVED** [review]

**Comment by yuvipanda** [comment]
I'm going to terraform apply this across our AWS clusters

**Comment by consideRatio** [comment]
I think there may be an issue if we specify a region where the GPU isn't available, but I'm not sure - maybe not. Could also have been resolved with updates to cluster-autoscaler understanding it shouldn't attempt to scale up in a zone where the relevant GPU to attach isn't available.

**Comment by yuvipanda** [comment]
The `terraform apply` only creates EFS Mount Target in all zones, so nodes *can* spawn there if needed. Only cryocloud is updated now.

Was there a previous issue with cluster-autoscaler around this?

**Comment by damianavila** [comment]
> I'm going to terraform apply this across our AWS clusters

@yuvipanda, can you confirm if this ⬆️ happened?

**Comment by consideRatio** [comment]
I did a sweep, this is now consistently applied across all AWS projects!

**Pull request merged**
