### PR TITLE
2i2c, climatematch: update authorized github users

### PR DESCRIPTION
**Pull request by iamzoltan**
Changes for the 2024 Climate Course at Neuromatch.

Is it possible for these changes to take effect May 1?

### CODE REVIEW

**Comment by consideRatio** [comment]
@iamzoltan I can get this merged 1st May during Swedish UTC+2 time's morning for example.

Abigail and Wesley are currently listed as the authorized personell to initiate support tickets to 2i2c. Could you ask one of them to email us at support@2i2c.org and confirm that you are allowed to propose changes in this infrastructure?

**Comment by iamzoltan** [comment]
@consideRatio That would be great, thank you!

I have already messaged support and they sent me here. I was added to the authorized personnel (not sure how long that needs to take effect).

**Comment by consideRatio** [comment]
> I have already messaged support and they sent me here. I was added to the authorized personnel (not sure how long that needs to take effect).

Are you Konstantine? Let us know from the support thread that you are working through the account `@iamzoltan` and we'll be set for a merge tomorrow!

**Comment by yuvipanda** [comment]
Verified via freshdesk in https://2i2c.freshdesk.com/a/tickets/1521

**Pull request merged**
