### PR TITLE
Bump utoronto image version to dfd2313d2617

### PR DESCRIPTION
**Pull request by pnasrat**
Includes packages requested as in  2i2c-org/utoronto-image#46

### CODE REVIEW

**Review by damianavila — APPROVED** [review]
LGTM

**Comment by pnasrat** [comment]
```
CalledProcessError: Command '['helm', 'upgrade', '--install', 
'--create-namespace', '--wait', '--namespace=prod', 'prod', 
PosixPath('/home/runner/work/infrastructure/infrastructure/helm-charts/basehub')
, '--values=/tmp/tmppjq6jhil', 
'--values=/home/runner/work/infrastructure/infrastructure/config/clusters/utoron
to/common.values.yaml', 
'--values=/home/runner/work/infrastructure/infrastructure/config/clusters/utoron
to/default-common.values.yaml', 
'--values=/home/runner/work/infrastructure/infrastructure/config/clusters/utoron
to/default-prod.values.yaml', '--values=/tmp/tmp_c5frbs4']' returned non-zero 
exit status 1.
Error: Process completed with exit code 1.
```

**Comment by pnasrat** [comment]
```
helm list -n prod
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS	CHART        	APP VERSION
prod	prod     	304     	2023-03-07 16:58:55.587200842 +0000 UTC	failed	basehub-0.1.0	1.0      
```

**Comment by pnasrat** [comment]
So looking at the top of the error we see that the step took 5m10s

image

The helm error is `Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition`

The defaulkt helm timeout is 5min so I think we are hitting this occasionally maybe we should set timeout in the github deployer run

https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback

**Comment by damianavila** [comment]
> The defaulkt helm timeout is 5min so I think we are hitting this occasionally maybe we should set timeout in the github deployer run

Yep, I concur. I use the timeout in the past in other deployments and worked great for some use cases.

**Pull request merged**
