### PR TITLE
new singleuser image for VEDA JHs

### PR DESCRIPTION
**Pull request by ranchodeluxe**
This is a new singleuser image with an updated version of `stac_ipyleaflet` plugin

### CODE REVIEW

**Comment by yuvipanda** [comment]
I had a quick chat with @ranchodeluxe and we're going to take a slightly different approach to this :)

**Comment by consideRatio** [comment]
> The only question I'm unsure of is if the post-start user is jovyan as [I set it up over here](https://github.com/NASA-IMPACT/veda-jh-environments/blob/main/docker-images/custom/nasa-veda-singleuser/Dockerfile#L5-L6)

A k8s postStart lifecycle hook in user pods are executed as user `1000` (aka. jovyan), because that container is specified to `runAsUser: 1000` by default by the JupyterHub Helm chart via `singleuser.uid`.

**Comment by consideRatio** [comment]
Marked as draft because Yuvi commented about another approach were to be taken.

**Comment by ranchodeluxe** [comment]
@yuvipanda and @consideRatio: can we remove the draft designation here please. This is one needed change I need in. Everything regarding `/veda-docs` additions will be in a separate PR. I've updated the title and description :thankyou:

**Pull request merged**
