### PR TITLE
Deploying helm components to linked earth cluster

### PR DESCRIPTION
**Pull request by sgibson91**
- Deploy the support chart
- Deploy two daskhubs: staging and prod

related https://github.com/2i2c-org/infrastructure/issues/1418

(This PR is branched from https://github.com/2i2c-org/infrastructure/pull/1476 and should be rebased against master before merging)

### CODE REVIEW

**Comment by sgibson91** [comment]
Currently blocked deploying the support chart due to following error message:

> Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "support-prometheus-server" namespace: "support" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

**Comment by yuvipanda** [comment]
my guess is it's because the cluster is new enough that [networking.k8s.io/v1beta1](http://networking.k8s.io/v1beta1) is removed, and it needs to be [networking.k8s.io/v1](http://networking.k8s.io/v1)

**Comment by yuvipanda** [comment]
So this might need a bump up of the prometheus chart (we're currently at 13.x, latest is 15.10.1). Some labels changed, so we might need https://github.com/jupyterhub/grafana-dashboards/pull/42 to be merged. This would impact prometheus on all clusters.

**Comment by sgibson91** [comment]
Commits are getting messy from working on two branches that are related but one isn't merged. I'm closing this and will just add all config to #1476

**Pull request closed without merging**
