### PR TITLE
Update OHW Python and R images, and some metadata

### PR DESCRIPTION
**Pull request by emiliom**
- Python and R images
- Labels for the images (to make them a bit more user friendly, in Spanish)
- Logo url

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks, @emiliom. Test it out once the deploy is done :)

**Comment by emiliom** [comment]
Wow, that was really fast @yuvipanda !! Thank you! I'll test it out in an hour or two.

**Comment by yuvipanda** [comment]
@emiliom haha, sometimes I anxiously refresh github notifications :D

**Comment by emiliom** [comment]
I've tested the hub with the two images. **The R image is failing.** RStudio doesn't come up and shows this error:

image

I haven't seen this before. @abkfenris , have you?

The hub deployment monitor showed this warning https://github.com/2i2c-org/infrastructure/actions/runs/4267187164/jobs/7428550251#step:5:35:
> Health check failed!
> Warning: Attempt 1 failed. Reason: Child_process exited with error code 1

Though it's just a warning.

The Python image works fine and the updates are there.

**Comment by yuvipanda** [comment]
@emiliom I looked at the logs, and found this:

```
[W 2023-02-25 01:52:24.555 SingleUserLabApp manager:360] jupyter_server_proxy | extension failed loading with message: DistributionNotFound(Requirement.parse('webcolors>=1.11; extra == "format-nongpl"'), {'jsonschema'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 356, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 228, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 228, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 219, in load_point
        return point.load(serverapp)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 147, in load
        return loader(serverapp)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server_proxy/__init__.py", line 30, in _load_jupyter_server_extension
        server_processes += get_entrypoint_server_processes(serverproxy_config)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server_proxy/config.py", line 83, in get_entrypoint_server_processes
        server_process_config = entry_point.load()()
      File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2476, in load
        self.require(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2499, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 815, in resolve
        dist = self._resolve_dist(
      File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 856, in _resolve_dist
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
```

This has prevented jupyter-server-proxy from being installed, and hence RStudio doesn't work. Often this is because of some version conflict in how things are installed.

We can revert the R image temporarily while you fix that if you want, or leave it as is.

**Comment by emiliom** [comment]
Thanks @yuvipanda . Hmm. Doing some research on that error message, the best I can come up with is that we need to add `jsonschema-with-format-nongpl` to the environment. It looks like an alternative build for `jsonschema` that's equivalent to `pip install jsonschema[format-nongpl]`. 

Does it look like I may be on the right track?

I can build a new image where I add `jsonschema-with-format-nongpl`, submit a new PR, and cross my fingers. What do you think?

Footnotes:
- There's a recent reference to this error, from 4 days ago: https://stackoverflow.com/questions/75511394/jupyter-contrib-nbextension-install-user-pkg-resources-distributionnotfound-we
- The [previous R image, built on 8/17/2022, used `jsonschema` 4.9.1](https://github.com/oceanhackweek/jupyter-image/blob/9a5415ee7ddcff5c3c781893d8bd83026e2d31b1/r/conda-linux-64.lock#L239). `jsonschema` 4.10.0 came out also on 8/17/2022, and it looks like it [caused some hiccups](https://github.com/python-jsonschema/jsonschema/issues/982), though I have no idea if it's related to the problem in this PR.
- The Python image has `jsonschema` 4.17.3, just like the R image that's failing.

**Comment by emiliom** [comment]
One more thing. In our R `Dockerfile`, we have this, [from last August](https://github.com/oceanhackweek/jupyter-image/blob/cf019b7723d024a863dc7060c3331e2ff5312b52/r/Dockerfile#L53):
```docker
# # Newer one has bug that doesn't work with jupyter-rsession-proxy
ENV RSTUDIO_URL https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2022.07.1-554-amd64.deb
```

I didn't update it. Don't know if I should.

**Comment by yuvipanda** [comment]
@emiliom I think trying jsonschema-with-format-nongpl is the way to go.

**Comment by yuvipanda** [comment]
I don't think this is related to the RStudio install. The error is coming from the jupyter-server-proxy package, a dependency of the jupyter-rsession-proxy package.

**Comment by emiliom** [comment]
PR #2253

**Pull request merged**
