### PR TITLE
Update hub image

### PR DESCRIPTION
**Pull request by GeorgianaElena**
This updates the hub image with the following:

- bumps `oauthenticator` from the commit it was pinned, to the latest `15.1.0` release
- bumps and pins `kubespawner` to this commit https://github.com/jupyterhub/kubespawner/commit/fa19acdbb056c8d105baab13bbaa2b8b59dfa962

It also puts the custom packages we're installing alogside their pinned versions inside a `requirement.txt` to be picked up by dependabot.

Closes https://github.com/2i2c-org/infrastructure/issues/1589 and closes https://github.com/2i2c-org/infrastructure/issues/1825

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by sgibson91** [comment]
I think for dependabot to pick up these files, we should remove this line from the config:

https://github.com/2i2c-org/infrastructure/blob/74b06d59a7bff32873995db46962568f3eebb501/.github/dependabot.yaml#L35

I _believe_ then dependabot will look for any requirements files anywhere in the repo

**Comment by sgibson91** [comment]
Also remember that merging this will overwrite what was done manually in https://github.com/2i2c-org/infrastructure/pull/1848

We should probably not wait for Yuvi to merge that and just do it now

**Comment by GeorgianaElena** [comment]
> I believe then dependabot will look for any requirements files anywhere in the repo, as opposed to just the root

Hmm, I actually thought that the `/` in the directory, meant *search recursively everywhere in `/`*, which should have meant everywhere.
Apparently, neither the `/`, nor leaving directory empty means *please go and search everywhere for such files* :/ as the `directory` is a **required** field. 

https://github.com/dependabot/dependabot-core/issues/3951 has more context about specifying multiple directories for dependabot. It looks like we need to list each individual location for the requirements file

**Comment by GeorgianaElena** [comment]
> We should probably not wait for Yuvi to merge that and just do it now

Good point! I will merge it before this one

**Comment by sgibson91** [comment]
RE dependabot: dang. Let's just merge as-is and I'll open a follow-up PR for dependabot

**Comment by sgibson91** [comment]
@GeorgianaElena I just went straight for the PR because I had the commit ready

- https://github.com/2i2c-org/infrastructure/pull/1855

**Comment by yuvipanda** [comment]
Thanks a lot for catching #1848 dependency, @sgibson91!

**Pull request merged**
