### PR TITLE
Add Tuskegee University and Fresno City College hubs

### PR DESCRIPTION
**Pull request by sean-morris**
Fresno City College is added to the cloudbank cluster and uses the
CILoginOAuthenticator strategy for authentication.

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
LGTM 🚀

**Review by damianavila — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
Small note: https://github.com/2i2c-org/infrastructure/pull/1403 will break this PR if merged first. Similarly if this one gets merged, the config we'll need to be updated when migrating to `oauthenticator 15.0`

**Comment by GeorgianaElena** [comment]
> Small note: https://github.com/2i2c-org/infrastructure/pull/1403 will break this PR if merged first.

I don't believe ⬆️ is true anymore since I don't see anything that's been deprecated being used here.

Also, @sean-morris I hope it's oke I've changed the title of the PR to signal that there are now two hubs that are being added.

LGTM 🚀

**Comment by sean-morris** [comment]
> > Small note: #1403 will break this PR if merged first.
> 
> I don't believe ⬆️ is true anymore since I don't see anything that's been deprecated being used here.
> 
> Also, @sean-morris I hope it's oke I've changed the title of the PR to signal that there are now two hubs that are being added.
> 
> LGTM 🚀

I wondered how I did that! I kept staring at the title going I really don't remember changing the name! Thank you.

**Pull request merged**
