### PR TITLE
catalystproject-latm bump filestore from 1TB to 4TB

### PR DESCRIPTION
**Pull request by jmunroe**

### CODE REVIEW

**Comment by jmunroe** [comment]
@yuvipanda is this the correct way to increase the quota on a GCP Filestore? Is a jump from 1TB to 4TB reasonable or is 1TB to 2TB a better practice.

**Comment by yuvipanda** [comment]
@jmunroe it is the correct way! I'd say going to 2TB is better practice.

I invited you to the gcp project, so i'd suggest you use the console to increase the size to unblock yourself. If you can update the PR to be 2TB, then someone from engineering can apply it when they get a chance.

**Comment by jmunroe** [comment]
Thanks @yuvipanda ! Ok, I  made the change on the GCP console to solve the immediate issue and updated the PR to change the Filestore to 2TB.

I leave it to one of the @2i2c-org/engineering team to actually do the terraform apply step and merge this PR.

**Comment by jmunroe** [comment]
Deployment is scheduled for June 18.

**Comment by yuvipanda** [comment]
This needs to be 6TB now

**Pull request closed without merging**
