### PR TITLE
Increase limit for LEAP dask nodes to 200 from 100

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://2i2c.freshdesk.com/a/tickets/273

### CODE REVIEW

**Comment by yuvipanda** [comment]
Looks like we don't have terraform autoformat on pre-commit, and it just auto-formatted this one.

**Comment by sgibson91** [comment]
A whole ago, I tried adding terraform stuff to pre-commit, but it wouldn't run on pre-commit.ci https://github.com/2i2c-org/infrastructure/pull/1246

**Comment by yuvipanda** [comment]
```
data.google_compute_network.default_network: Reading...
google_service_account.cd_sa: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-cd-sa@leap-pangeo.iam.gserviceaccount.com]
data.google_client_config.default: Reading...
data.google_compute_subnetwork.default_subnetwork: Reading...
google_service_account.cluster_sa: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_custom_role.requestor_pays: Refreshing state... [id=projects/leap-pangeo/roles/leap_requestor_pays]
google_storage_bucket.user_buckets["persistent"]: Refreshing state... [id=leap-persistent]
google_storage_bucket.user_buckets["persistent-staging"]: Refreshing state... [id=leap-persistent-staging]
google_storage_bucket.user_buckets["scratch"]: Refreshing state... [id=leap-scratch]
google_storage_bucket.user_buckets["scratch-staging"]: Refreshing state... [id=leap-scratch-staging]
data.google_client_config.default: Read complete after 0s [id=projects//regions//zones/]
google_service_account.workload_sa["prod"]: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-prod@leap-pangeo.iam.gserviceaccount.com]
google_service_account.workload_sa["staging"]: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-staging@leap-pangeo.iam.gserviceaccount.com]
google_service_account_key.cd_sa: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-cd-sa@leap-pangeo.iam.gserviceaccount.com/keys/8192f1f77328895d53a3c3c2cb53cefa78cb4cc5]
google_project_iam_member.cd_sa_roles["roles/artifactregistry.writer"]: Refreshing state... [id=leap-pangeo/roles/artifactregistry.writer/serviceAccount:leap-cd-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cd_sa_roles["roles/container.admin"]: Refreshing state... [id=leap-pangeo/roles/container.admin/serviceAccount:leap-cd-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/artifactregistry.reader"]: Refreshing state... [id=leap-pangeo/roles/artifactregistry.reader/serviceAccount:leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/logging.logWriter"]: Refreshing state... [id=leap-pangeo/roles/logging.logWriter/serviceAccount:leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/monitoring.metricWriter"]: Refreshing state... [id=leap-pangeo/roles/monitoring.metricWriter/serviceAccount:leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/monitoring.viewer"]: Refreshing state... [id=leap-pangeo/roles/monitoring.viewer/serviceAccount:leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/stackdriver.resourceMetadata.writer"]: Refreshing state... [id=leap-pangeo/roles/stackdriver.resourceMetadata.writer/serviceAccount:leap-cluster-sa@leap-pangeo.iam.gserviceaccount.com]
data.google_compute_subnetwork.default_subnetwork: Read complete after 0s [id=projects/leap-pangeo/regions/us-central1/subnetworks/default]
google_storage_bucket_iam_member.member["staging.persistent-staging"]: Refreshing state... [id=b/leap-persistent-staging/roles/storage.admin/serviceAccount:leap-staging@leap-pangeo.iam.gserviceaccount.com]
data.google_compute_network.default_network: Read complete after 0s [id=projects/leap-pangeo/global/networks/default]
google_storage_bucket_iam_member.member["staging.scratch-staging"]: Refreshing state... [id=b/leap-scratch-staging/roles/storage.admin/serviceAccount:leap-staging@leap-pangeo.iam.gserviceaccount.com]
google_storage_bucket_iam_member.member["prod.scratch"]: Refreshing state... [id=b/leap-scratch/roles/storage.admin/serviceAccount:leap-prod@leap-pangeo.iam.gserviceaccount.com]
google_storage_bucket_iam_member.member["prod.persistent"]: Refreshing state... [id=b/leap-persistent/roles/storage.admin/serviceAccount:leap-prod@leap-pangeo.iam.gserviceaccount.com]
google_service_account_iam_binding.workload_identity_binding["prod"]: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-prod@leap-pangeo.iam.gserviceaccount.com/roles/iam.workloadIdentityUser]
google_service_account_iam_binding.workload_identity_binding["staging"]: Refreshing state... [id=projects/leap-pangeo/serviceAccounts/leap-staging@leap-pangeo.iam.gserviceaccount.com/roles/iam.workloadIdentityUser]
google_container_cluster.cluster: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster]
google_filestore_instance.homedirs[0]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1-c/instances/leap-homedirs]
google_project_iam_member.requestor_pays_binding["prod"]: Refreshing state... [id=leap-pangeo/projects/leap-pangeo/roles/leap_requestor_pays/serviceAccount:leap-prod@leap-pangeo.iam.gserviceaccount.com]
google_project_iam_member.requestor_pays_binding["staging"]: Refreshing state... [id=leap-pangeo/projects/leap-pangeo/roles/leap_requestor_pays/serviceAccount:leap-staging@leap-pangeo.iam.gserviceaccount.com]
google_container_node_pool.notebook["medium"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/nb-medium]
google_container_node_pool.core: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/core-pool]
google_container_node_pool.notebook["small"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/nb-small]
google_container_node_pool.notebook["gpu-t4"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/nb-gpu-t4]
google_container_node_pool.dask_worker["medium"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-medium]
google_container_node_pool.dask_worker["small"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-small]
google_container_node_pool.dask_worker["large"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-large]
google_container_node_pool.notebook["huge"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/nb-huge]
google_container_node_pool.dask_worker["huge"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-huge]
google_container_node_pool.notebook["large"]: Refreshing state... [id=projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/nb-large]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_container_node_pool.dask_worker["huge"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-huge"
        name                        = "dask-huge"
        # (9 unchanged attributes hidden)

      ~ autoscaling {
          ~ max_node_count = 100 -> 200
            # (1 unchanged attribute hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["large"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-large"
        name                        = "dask-large"
        # (9 unchanged attributes hidden)

      ~ autoscaling {
          ~ max_node_count = 100 -> 200
            # (1 unchanged attribute hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["medium"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-medium"
        name                        = "dask-medium"
        # (9 unchanged attributes hidden)

      ~ autoscaling {
          ~ max_node_count = 100 -> 200
            # (1 unchanged attribute hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["small"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/leap-pangeo/locations/us-central1/clusters/leap-cluster/nodePools/dask-small"
        name                        = "dask-small"
        # (9 unchanged attributes hidden)

      ~ autoscaling {
          ~ max_node_count = 100 -> 200
            # (1 unchanged attribute hidden)
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.

Do you want to perform these actions in workspace "leap"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

is terraform plan output

**Comment by yuvipanda** [comment]
I checked quota, there are 5000 CPU core quotas for preemptible instances so we're good there.

**Pull request merged**
