### PR TITLE
LIS hub extra mount point

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Closes https://github.com/2i2c-org/infrastructure/issues/1801

- [x] deploy change
- [x] document feature
         - https://github.com/2i2c-org/docs/pull/166
         - https://github.com/2i2c-org/infrastructure/pull/1811/commits/7d09ffc25b9bea9dd1ba62fb9f4f7823a951eb6c

### CODE REVIEW

**Review by damianavila — APPROVED** [review]
LGTM, thanks for the docs addition!!

**Comment by damianavila** [comment]
>  deploy change

@GeorgianaElena, it seems you already deployed the change (maybe manually?) to address the request quickly?

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena, it seems you already deployed the change (maybe manually?) to address the request quickly?

Yes, it should already be available in https://ds.lis.2i2c.cloud

**Comment by sgibson91** [comment]
I'm a little bit unclear on the docs. I thought we still use NFS protocol when we use a cloud-based filestore, we just don't have to manually set it up like we do if we're provisioning a VM. But it's possible I misunderstood?

**Pull request merged**
