### PR TITLE
Bump version of configurator

### PR DESCRIPTION
**Pull request by yuvipanda**
Brings in https://github.com/yuvipanda/jupyterhub-configurator/pull/7

### CODE REVIEW

**Comment by yuvipanda** [comment]
Will need to be decoupled from the hub image soon, so we can iterate on the configurator faster / better.

**Review by GeorgianaElena — APPROVED** [review]
:crossed_fingers:

**Review by damianavila — APPROVED** [review]

**Comment by choldgraf** [comment]
any reason this is still in draft mode? when will it be time to merge this?

**Comment by damianavila** [comment]
@yuvipanda, do you want to do anything else here before migrating this one off the draft state?

**Comment by yuvipanda** [comment]
@damianavila i think this won't actually work - right now, configurator ships with built js in the repo (https://github.com/yuvipanda/jupyterhub-configurator/blob/main/jupyterhub_configurator/static/index.js) and I think the last PR didn't actually commit the built JS

**Comment by GeorgianaElena** [comment]
@yuvipanda, @damianavila , sorry about missing to add that file to the PR. I opened https://github.com/yuvipanda/jupyterhub-configurator/pull/12 to address this.

**Comment by damianavila** [comment]
Do we want to also merge https://github.com/yuvipanda/jupyterhub-configurator/pull/11 before updating this one with a new tag?

**Comment by consideRatio** [comment]
I'll pre-emptively close this as it seems no longer relevant.

**Pull request closed without merging**
