### PR TITLE
Use OPTIMIZE_UTILIZATION cluster autoscaler profile

### PR DESCRIPTION
**Pull request by yuvipanda**
GKE supports setting a cluster autoscaler profile that
optimizes utilization[1]. This changes the behavior of
the autoscaler *and* the scheduler, packing pods in tighter
into nodes rather than 'spreading' them around. This is
what the z2jh user-scheduler primarily does. We can actually
do away with the user-scheduler if we use the OPTIMIZE_UTILIZATION
autoscaler profile - Berkeley has been running under this setup
for a few months now. This reduces how much resources our core
nodes need, and the GKE provided scheduler is also faster.
This will also prevent issues like
https://github.com/2i2c-org/infrastructure/issues/1004.

[1]: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#autoscaling_profiles

### CODE REVIEW

**Comment by choldgraf** [comment]
Is there any downside to doing this? It seems pretty reasonable to me!

**Comment by sgibson91** [comment]
It would be nice to see a terraform plan for a cluster so we know if this change will be destructive or not. I am +1 on merging it if we don't need down-time to apply the changes to our clusters.

**Comment by damianavila** [comment]
> And I think that the Toronto folks will be happy to learn that we've improved the pod packing logic!

@choldgraf, see this comment from Yuvi in #1004:

> I don't think such a thing is possible in AKS yet.

**Comment by damianavila** [comment]
> We can actually do away with the user-scheduler if we use the OPTIMIZE_UTILIZATION autoscaler profile

Do you want to open a follow-up issue to track that removal in the future?

**Comment by yuvipanda** [comment]
@sgibson91 for some reason, pilot hubs and cloudbank already have the autoscaler set to this mode?!

Here's the plan for meom-ige:


```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_container_node_pool.dask_worker["huge"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/dask-huge"
        name                        = "dask-huge"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["large"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/dask-large"
        name                        = "dask-large"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["medium"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/dask-medium"
        name                        = "dask-medium"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["small"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/dask-small"
        name                        = "dask-small"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.dask_worker["very-large"] will be updated in-place
  ~ resource "google_container_node_pool" "dask_worker" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/dask-very-large"
        name                        = "dask-very-large"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.notebook["huge"] will be updated in-place
  ~ resource "google_container_node_pool" "notebook" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/nb-huge"
        name                        = "nb-huge"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.notebook["large"] will be updated in-place
  ~ resource "google_container_node_pool" "notebook" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/nb-large"
        name                        = "nb-large"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.notebook["medium"] will be updated in-place
  ~ resource "google_container_node_pool" "notebook" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/nb-medium"
        name                        = "nb-medium"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.notebook["small"] will be updated in-place
  ~ resource "google_container_node_pool" "notebook" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/nb-small"
        name                        = "nb-small"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

  # google_container_node_pool.notebook["very-large"] will be updated in-place
  ~ resource "google_container_node_pool" "notebook" {
        id                          = "projects/meom-ige-cnrs/locations/us-central1-b/clusters/meom-ige-cluster/nodePools/nb-very-large"
        name                        = "nb-very-large"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode = "MODE_UNSPECIFIED"
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 10 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│ 
│   with google_filestore_instance.homedirs,
│   on storage.tf line 4, in resource "google_filestore_instance" "homedirs":
│    4:   zone = var.zone
│ 
│ Deprecated in favor of location.
```

Most of the changes are unrelated, and I think meom-ige also has this set by default...

**Comment by yuvipanda** [comment]
This terraform plan was also after applying https://github.com/2i2c-org/infrastructure/pull/1035, as I couldn't get `plan` to work without bumping versions.

**Comment by yuvipanda** [comment]
I also opened https://github.com/2i2c-org/infrastructure/issues/1034 to reduce confusion about our workspaces.

**Review by sgibson91 — APPROVED** [review]
Thanks for the updates and hard work on this @yuvipanda, this LGTM!

**Comment by choldgraf** [comment]
I just had a thought - could we run regression tests on terraform plan? e.g., could we:

- Run `terraform plan` with our config
- Write the output to a file
- Check that file into our github repository, one for each cluster
- In CI/CD, do a quick `diff` comparison between the two and do something to highlight the difference

I do this with pytest-regressions a lot and have found it a useful workflow.

**Comment by sgibson91** [comment]
The terraform plan is already a diff so I don't think diffing 2 plans will be useful, especially if they touch different parts of the infrastructure and have no overlap.

What you'd actually want to run a diff on is the state file (and that is exactly what terraform plan does), but we can't check that into version control as secrets are not encrypted in the state.

**Comment by choldgraf** [comment]
ah I see, I think I am exposing my ignorance of what `terraform plan` really does 😅

**Comment by choldgraf** [comment]
Hey all - can we merge this or is it waiting on something?

**Comment by yuvipanda** [comment]
I'm going to have to deploy this on all our GCP workspaces, which would probably also mean cleaning up https://github.com/2i2c-org/infrastructure/issues/1034 along the way.

**Comment by yuvipanda** [comment]
Done for everything except the pangeo hubs.

**Comment by yuvipanda** [comment]
Done for everything now

**Comment by yuvipanda** [comment]
> > We can actually do away with the user-scheduler if we use the OPTIMIZE_UTILIZATION autoscaler profile
> 
> Do you want to open a follow-up issue to track that removal in the future?

@damianavila i opened https://github.com/2i2c-org/infrastructure/pull/1126

**Comment by damianavila** [comment]
Thanks!

**Pull request merged**
