### PR TITLE
Bump prometheus volume size for 2i2c shared cluster

### PR DESCRIPTION
**Pull request by yuvipanda**
100Gi filled up on 30/6

Discovered by looking at https://grafana.pilot.2i2c.cloud/d/bUnRC_Qnz/nfs-and-support-information?orgId=1

### CODE REVIEW

**Comment by pnasrat** [comment]
Any reason not to give it 512 or 1T - basically a laptop disk prior to actually capacity planning

**Comment by yuvipanda** [comment]
None! bumped to 1Ti

**Comment by yuvipanda** [comment]
I've actually bumped it up to 512Gi instead, as I don't know if we'll cross that threshold with only 1y of retention. And we can resize up, but not down.

**Review by pnasrat — APPROVED** [review]
LGTM

**Comment by yuvipanda** [comment]
Thanks @pnasrat

**Pull request merged**
