### PR TITLE
Remove K80 GPUs from uwhackweeks hub

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/2i2c-org/infrastructure/issues/1765

### CODE REVIEW

**Comment by yuvipanda** [comment]
@scottyhq is this ok with you?

**Review by sgibson91 — APPROVED** [review]
Pending Scott's approval

**Review by scottyhq — APPROVED** [review]
thanks!

**Comment by yuvipanda** [comment]
Thanks @scottyhq and @sgibson91

**Comment by yuvipanda** [comment]
Done via `eksctl delete nodegroup --cluster=uwhackweeks --include=nb-p2-xlarge`

**Pull request merged**
