### PR TITLE
Fix deprecated attributes in terraform config

### PR DESCRIPTION
**Pull request by sgibson91**
While working on #761, I came across the following warning about a deprecated attribute from terraform:

> Warning: Deprecated Attribute
> 
>   with google_container_node_pool.notebook["small"],
>   on cluster.tf line 199, in resource "google_container_node_pool" "notebook":
>  199:       node_metadata = var.config_connector_enabled ? "GKE_METADATA_SERVER" : "SECURE"
> 
> Deprecated in favor of mode.

And then subsequently, the following deprecation warning:

> Warning: Deprecated Attribute
> 
>   with google_container_cluster.cluster,
>   on cluster.tf line 1, in resource "google_container_cluster" "cluster":
>    1: resource "google_container_cluster" "cluster" {
> 
> This field will be removed in a future major release as it has been deprecated in the API. Use `workload_pool` instead.

This PR changes all (2) instances of the `node_metadata` attribute to `mode` and updates the values appropriately. It also changes the `identity_namespace` attribute to `workload_pool`.

See terraform docs here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#mode

### CODE REVIEW

**Comment by sgibson91** [comment]
@damianavila That is an excellent question that I do not have the answer to. I think this came up as a "changes have happened outside terraform" though, so it may be that we only need to do a `-refresh-only` plan to get our state up-to-date.

**Comment by sgibson91** [comment]
Sorry @damianavila, do you mind reviewing again? I think I forgot to commit/push the changes I made to the _values_ of `node_metadata`/`mode` as they changed with the new attribute too.

**Comment by sgibson91** [comment]
So at least for Pangeo, this would be a refresh-only change. That is to say, google has already made these updates upstream, and we are now making our terraform state match google's state. No redeploy is necessary.

Logs:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":
[snip]
  # google_container_node_pool.notebook["large"] has been changed
  ~ resource "google_container_node_pool" "notebook" {
        id                  = "projects/pangeo-integration-te-3eea/locations/us-central1-b/clusters/pangeo-hubs-cluster/nodePools/nb-large"
        name                = "nb-large"
        # (9 unchanged attributes hidden)



      ~ node_config {
            tags              = []
            # (12 unchanged attributes hidden)


          ~ workload_metadata_config {
              + mode          = "GKE_METADATA"
                # (1 unchanged attribute hidden)
            }
            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
[snip]
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```

Steps to refresh the terraform state:

```
cd terraform/gcp
tf init -backend-config=../backends/<BACKEND_FILE> -reconfigure
tf plan -var-file=projects/<CLUSTER_FILE> -out=<PLAN_NAME> -refresh-only
tf apply <PLAN_NAME>
```

**Comment by damianavila** [comment]
> It is unfortunate that they also seem to have deprecated the SECURE setting 😕

Yep, I am worried about the implications of the new UNSPECIFIED setting...

@yuvipanda do you have any thoughts about this?

Btw, given this context: https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment, maybe we need to start thinking about abandoning the metadata concealment option?

**Pull request merged**
