### PR TITLE
Add autoformatting to terraform code

### PR DESCRIPTION
**Pull request by yuvipanda**
Uses terraform_fmt with defualt options.

### CODE REVIEW

**Review by pnasrat — APPROVED** [review]
LGTM

**Comment by yuvipanda** [comment]
Unfortunately pre-commit.ci is failing because it does not have `terraform` installed so i'm shaving a yak somewhere in nepal...

**Comment by yuvipanda** [comment]
@pnasrat ok, so yak has been shaved and there's now a new pre-commit, using https://github.com/yuvipanda/terraform-bin. Does this still look good to you? I could also move that pre-commit hook into the 2i2c org instead of my personal repo.

**Comment by pnasrat** [comment]
LGTM

I think for now it's ok in a personal repo

At some point as an org we probably want to figure what should live under the org repo/best practices on that but that can wait for another day!

**Comment by yuvipanda** [comment]
Thanks, @pnasrat!

**Comment by sgibson91** [comment]
> pre-commit.ci is failing because it does not have `terraform` installed

This is exactly the problem I ran into when I tried to implement this ages ago. Thank you for figuring out a solution!

**Pull request merged**
