### PR TITLE
Add new image option for LEAP classes

### PR DESCRIPTION
**Pull request by jbusecke**
I would like to test a custom image (details overe [here](https://github.com/jbusecke/leap_education_docker_image), made according to the instructions [here](https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html?highlight=image#create-a-custom-user-image-for-your-hub)). If I understand correctly using the ['configurator'](https://pilot.2i2c.org/en/latest/admin/howto/configurator.html) this will change the image for every user starting a new server (which I want to avoid at all cost rn, since this is very early testing 😬). 

Ultimately I would like to have an option to pull arbitrary images using tags (but I will send a separate email for that, also cc @jmunroe, who might have already raised this more general issue).

### CODE REVIEW

**Comment by sgibson91** [comment]
Is testing the image on the staging hub not possible? https://staging.leap.2i2c.cloud You can use the configurator on that hub without affecting users on the prod hub because it's a whole separate JupyterHub.

**Comment by jbusecke** [comment]
Ah, that makes a lot of sense! Let me test and report back!

**Comment by sgibson91** [comment]
Actually, the reason the configurator probably doesn't work because the hubs use `profileList` and the configurator isn't compatible with that yet.

**Comment by jbusecke** [comment]
I got an error with this: 
image

not sure if that is consistent. 

How about an alternate proposal: 
I can modify this PR to offer an additional image selection (which will be needed by the LEAP instructors and students soon). This might however require some version bumps if things are not behaving as expected? 

To make this abundantly clear I can add `(Testing Prototype)` to the description?

**Comment by sgibson91** [comment]
The 401 Unauthorised error makes me think that your quay.io repo is private, not public.

**Comment by jbusecke** [comment]
You were right, I just changed that. Sorry for the baby mistakes here. Pretty new to all of this.

So now I was able to start a server, but the image still seems to be the default pangeo-notebook (not quite sure how to confirm this, but the dependencies I need are definitely not there, and a bunch of the pangeo packages are installed instead). Is that the behavior you expected to see?

**Comment by jbusecke** [comment]
I was actually able to test this image by selecting one of the server instances without a dropdown menu (here `Small`), and everything looks like it works to me. 

I also added some words to the docs about making the image repo public [here](https://github.com/2i2c-org/docs/pull/181) (in the hope it might help future folks...or maybe future me hehe). 

With this working I would like to get this image option exposed so that the educators can develop their material directly on the hub. 

Thanks for the detailed help here @sgibson91! I really appreciate it.

**Comment by sgibson91** [comment]
> So now I was able to start a server, but the image still seems to be the default pangeo-notebook (not quite sure how to confirm this, but the dependencies I need are definitely not there, and a bunch of the pangeo packages are installed instead). Is that the behavior you expected to see?

> I was actually able to test this image by selecting one of the server instances without a dropdown menu (here `Small`), and everything looks like it works to me.

The reason you see this behaviour is because the configurator can only override images that are defined in this section of the JupyterHub config:

https://github.com/2i2c-org/infrastructure/blob/a591bc4f486cac521ec35018b76438d32242d341/config/clusters/leap/common.values.yaml#L61-L63

Any of the images that have dropdown menus, and are nested under `profileList`, **cannot** be overridden by the configurator. So yes this is expected behaviour. Not ideal behaviour, but expected. We do have a longstanding issue open to allow arbitrary selection of any tags in an image repo here: https://github.com/2i2c-org/infrastructure/issues/1253

> I also added some words to the docs about making the image repo public [here](https://github.com/2i2c-org/docs/pull/181)

Thank you so much for the PR!

**Review by sgibson91 — APPROVED** [review]

**Pull request merged**
