### PR TITLE
Save cilogon administrative client creds

### PR DESCRIPTION
**Pull request by GeorgianaElena**
I've filled in the form in https://cilogon.org/oauth2/admin-register (`2i2c` client name and I used the support email) and it generated this creds. Once the client gets approved we should be able to use them. But until then, let's store them somewhere safe (the old ones will probably become obsolete, but let's keep them both until we figure out the new auth infra ?? )

Ref: https://github.com/2i2c-org/infrastructure/issues/967

### CODE REVIEW

**Comment by sgibson91** [comment]
Hey @GeorgianaElena, this PR will create a conflict with https://github.com/2i2c-org/infrastructure/pull/1027

I suggest:

1. Wait til #1027 is merged
2. Rename `shared/deployer/enc-auth0-credentials.secret.yaml` to something sensible: `shared/deployer/enc-auth-provider-credentials.secret.yaml`?
3. Add the CILogon credentials to that file

Does that sound OK?

**Comment by GeorgianaElena** [comment]
@sgibson91, of course!

**Comment by GeorgianaElena** [comment]
I've rebased the PR @sgibson91. Also, this new client has recently been approved by CILogon folks :rocket: We just need to figure out how to use it

**Review by sgibson91 — APPROVED** [review]
@GeorgianaElena I pushed a commit to update the hard-coded path in the deployer, otherwise this is great - thank you!!

**Review by choldgraf — APPROVED** [review]
Just to confirm - this is embedding the CILogon API credentials in our secrets, so that we could re-use them in subsequent iterations in setting up CILogon with our stack. Is that right? That sounds good to me!

**Pull request merged**
