### PR TITLE
Enable cryptnono on all our clusters

### PR DESCRIPTION
**Pull request by yuvipanda**
https://github.com/yuvipanda/cryptnono/ is now deployed
on mybinder.org. We've already had a few incidents with
cryptomining (OpenScapes, cloudbank, pangeo binder). This
should help with that.

### CODE REVIEW

**Comment by choldgraf** [comment]
We should def document this, it is a big feature IMO ! Is that ok or would that not be a good idea from a "security through obscurity POV"?

**Comment by yuvipanda** [comment]
@choldgraf we should definitely document this!

**Comment by choldgraf** [comment]
I gave a first shot at this here:

- https://github.com/2i2c-org/docs/pull/147

would love feedback!

**Comment by damianavila** [comment]
Let's keep this one in the back of our heads in case it is related to the #1423 incident.

**Pull request merged**
