### PR TITLE
deployer: add the option to pass the debug flag to helm when deploying hubs

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Ref: https://github.com/2i2c-org/infrastructure/issues/2205#issuecomment-1453716299 and https://github.com/2i2c-org/infrastructure/issues/1917

Wished I had this when debugging #2349 😅

### CODE REVIEW

**Review by pnasrat — CHANGES_REQUESTED** [review]
This is great. If it's not too work I've  a suggestion for another flag that maps to `--dry-run --debug` or just allows `--dry-run` to also be set per

https://helm.sh/docs/chart_template_guide/debugging/

**Comment by GeorgianaElena** [comment]
> This is great. If it's not too work I've a suggestion for another flag that maps to --dry-run --debug or just allows --dry-run to also be set per

Yep, this is a very good idea. I will do that.

I also realized that I also missed updating the deployer readme.

**Review by pnasrat — APPROVED** [review]
lgtm

**Review by consideRatio — APPROVED** [review]
LGTM and should be fine to iterate on later without trouble if we decide to change something in this implementation.

**Pull request merged**
