### PR TITLE
Use a map of maps to define filestores, rather than a list of maps

### LINKED ISSUE #4334: Support creating multiple Filestore instances via Terraform on GCP
In order to do https://github.com/2i2c-org/infrastructure/issues/4257, we must be able to create multiple GCP filestores instances on Terraform. That way, we can perform the steps in https://github.com/2i2c-org/infrastructure/issues/4257#issuecomment-2196189509 and decomission the old filestore, rather than fiddle around with `terraform state`.

### PR DESCRIPTION
**Pull request by sgibson91**
- fixes #4334

### CODE REVIEW

**Comment by sgibson91** [comment]
When we run a plan with this config change against `pilot-hubs`, we get the following output

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # google_container_cluster.cluster will be updated in-place
  ~ resource "google_container_cluster" "cluster" {
        id                          = "projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster"
        name                        = "pilot-hubs-cluster"
        # (29 unchanged attributes hidden)

        # (23 unchanged blocks hidden)
    }

  # google_filestore_instance.homedirs["filestore"] will be created
  + resource "google_filestore_instance" "homedirs" {
      + create_time = (known after apply)
      + etag        = (known after apply)
      + id          = (known after apply)
      + location    = "us-central1-b"
      + name        = "pilot-hubs-homedirs"
      + project     = "two-eye-two-see"
      + tier        = "BASIC_HDD"
      + zone        = (known after apply)

      + file_shares {
          + capacity_gb   = 5120
          + name          = "homes"
          + source_backup = (known after apply)
        }

      + networks {
          + connect_mode      = "DIRECT_PEERING"
          + ip_addresses      = (known after apply)
          + modes             = [
              + "MODE_IPV4",
            ]
          + network           = "default"
          + reserved_ip_range = (known after apply)
        }
    }

  # google_monitoring_notification_channel.pagerduty_disk_space will be updated in-place
  ~ resource "google_monitoring_notification_channel" "pagerduty_disk_space" {
        id           = "projects/two-eye-two-see/notificationChannels/2203982305292521130"
        name         = "projects/two-eye-two-see/notificationChannels/2203982305292521130"
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # google_service_account_key.cd_sa will be updated in-place
  ~ resource "google_service_account_key" "cd_sa" {
        id                 = "projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com/keys/ee245c75f6c3fa5a36ae59597b356f4c6da80334"
        name               = "projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com/keys/ee245c75f6c3fa5a36ae59597b356f4c6da80334"
        # (8 unchanged attributes hidden)
    }

  # google_service_account_key.registry_sa_keys["binder-staging"] will be updated in-place
  ~ resource "google_service_account_key" "registry_sa_keys" {
        id                 = "projects/two-eye-two-see/serviceAccounts/binder-staging-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/195042aa9b5edc2b3502736bd2d99daa7c5c9877"
        name               = "projects/two-eye-two-see/serviceAccounts/binder-staging-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/195042aa9b5edc2b3502736bd2d99daa7c5c9877"
        # (8 unchanged attributes hidden)
    }

  # google_service_account_key.registry_sa_keys["binderhub-ui-demo"] will be updated in-place
  ~ resource "google_service_account_key" "registry_sa_keys" {
        id                 = "projects/two-eye-two-see/serviceAccounts/binderhub-ui-demo-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/7ad6294d83c8adb31c2e286e56f61a7d9f447f13"
        name               = "projects/two-eye-two-see/serviceAccounts/binderhub-ui-demo-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/7ad6294d83c8adb31c2e286e56f61a7d9f447f13"
        # (8 unchanged attributes hidden)
    }

Plan: 1 to add, 5 to change, 0 to destroy.
╷
│ Error: Instance cannot be destroyed
│ 
│   on storage.tf line 1:
│    1: resource "google_filestore_instance" "homedirs" {
│ 
│ Resource google_filestore_instance.homedirs[0] has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan,
│ either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
╵
```

This is because terraform is trying to move `google_filestore_instance.homedirs[0]` to `google_filestore_instance.homedirs["filestore"]` (even though both filestores ahve the same name and other identical properties).

**Comment by sgibson91** [comment]
I am going to see if I can rename the resource using `terraform state`

**Comment by sgibson91** [comment]
I ran `tf state mv 'google_filestore_instance.homedirs[0]' 'google_filestore_instance.homedirs["filestore"]'` and now the output of terraform plan is:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_container_cluster.cluster will be updated in-place
  ~ resource "google_container_cluster" "cluster" {
        id                          = "projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster"
        name                        = "pilot-hubs-cluster"
        # (29 unchanged attributes hidden)

        # (23 unchanged blocks hidden)
    }

  # google_monitoring_notification_channel.pagerduty_disk_space will be updated in-place
  ~ resource "google_monitoring_notification_channel" "pagerduty_disk_space" {
        id           = "projects/two-eye-two-see/notificationChannels/2203982305292521130"
        name         = "projects/two-eye-two-see/notificationChannels/2203982305292521130"
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # google_service_account_key.cd_sa will be updated in-place
  ~ resource "google_service_account_key" "cd_sa" {
        id                 = "projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com/keys/ee245c75f6c3fa5a36ae59597b356f4c6da80334"
        name               = "projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com/keys/ee245c75f6c3fa5a36ae59597b356f4c6da80334"
        # (8 unchanged attributes hidden)
    }

  # google_service_account_key.registry_sa_keys["binder-staging"] will be updated in-place
  ~ resource "google_service_account_key" "registry_sa_keys" {
        id                 = "projects/two-eye-two-see/serviceAccounts/binder-staging-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/195042aa9b5edc2b3502736bd2d99daa7c5c9877"
        name               = "projects/two-eye-two-see/serviceAccounts/binder-staging-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/195042aa9b5edc2b3502736bd2d99daa7c5c9877"
        # (8 unchanged attributes hidden)
    }

  # google_service_account_key.registry_sa_keys["binderhub-ui-demo"] will be updated in-place
  ~ resource "google_service_account_key" "registry_sa_keys" {
        id                 = "projects/two-eye-two-see/serviceAccounts/binderhub-ui-demo-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/7ad6294d83c8adb31c2e286e56f61a7d9f447f13"
        name               = "projects/two-eye-two-see/serviceAccounts/binderhub-ui-demo-registry-sa@two-eye-two-see.iam.gserviceaccount.com/keys/7ad6294d83c8adb31c2e286e56f61a7d9f447f13"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 5 to change, 0 to destroy.
```

**Comment by sgibson91** [comment]
I have updated the state of all the clusters so this now applies cleanly

**Comment by consideRatio** [comment]
Ah nice - thanks for writing things down here @sgibson91 - I appreciate knowing this was possible!

**Comment by GeorgianaElena** [comment]
@sgibson91, I ran into this while doing similar work for AWS and did a plan on the pilot-hubs cluster to understand if I need to run `terraform state mv` on all aws clusters and I'm still seeing the error.

> I have updated the state of all the clusters so this now applies cleanly

Based on this I had assumed this should not have been the case. Am I missing any extra step?

**Comment by sgibson91** [comment]
@GeorgianaElena I'm confused - did you run the `terraform state mv` command and you're still seeing the error after doing so?

**Comment by sgibson91** [comment]
> Based on this I had assumed this should not have been the case. Am I missing any extra step?

It _had_ to be the case because the instance was changing from `[..].homedirs[0]` to `[...].homedirs["filestore"]`, so the `terraform state mv` command _needs_ to be run for all clusters. No getting around it.

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena I'm confused - did you run the terraform state mv command and you're still seeing the error after doing so?

@sgibson91, no, I just ran a `terraform plan` on the pilot-hubs cluster on GCP and thought I saw a similar error, but I think it's different and it's related to backups instead. So please ignore my previous comment

Not sure if it's relevant, but here it is.

Screenshot 2024-07-25 at 16 00 29

**Comment by sgibson91** [comment]
@GeorgianaElena Ah yeah, I think that's likely a backup I created manually as well, so probably safe to run.

**Comment by sgibson91** [comment]
You can always try a `-refresh-only` plan as well

**Pull request merged**
