### PR TITLE
Remove justice innovation lab hub and cluster config

### PR DESCRIPTION
**Pull request by GeorgianaElena**
This removes the justice innovation cluster and `staging`/`prod` configs.
Reference https://github.com/2i2c-org/infrastructure/issues/990

### Things still left on the todo list:

- [ ] Remove the hub deployment ? (might be obsolete?)
- [x] Delete the Auth0 applications (for staging and prod)
- [ ] Remove the cluster, **BUT without deleting the container registry**

### Observations
- from the lack of secrets and the state of the deploy workflow, I don't believe the justice innovation lab hubs were ever deployed from the CI
- the justice innovation lab folks were using their own Azure account + credits and I believe the only @2i2c-org/tech-team member with access to this cluster is @yuvipanda

Since I don't believe I have access to the cluster, @yuvipanda, do you mind if I assign you to [this](https://github.com/2i2c-org/infrastructure/issues/990) instead and you'll delete the cluster (preserving the ACR)?

### CODE REVIEW

**Comment by sgibson91** [comment]
> * from the lack of secrets and the state of the deploy workflow, I don't believe the justice innovation lab hubs were ever deployed from the CI

I think there was a remnant hub on the 2i2c cluster. But I don't believe the JIL cluster was automatically deployed from CI.

**Review by yuvipanda — APPROVED** [review]
yes, am happy to take that on, @GeorgianaElena!

**Comment by yuvipanda** [comment]
https://stackoverflow.com/a/55271805 seems the appropriate way to 'delete everything except ACR', and I've already run the relevant `terraform` command. However, it looks like maybe I don't actually have access anymore either! I've pinged on the issue.

**Comment by yuvipanda** [comment]
@GeorgianaElena can you remove `terraform/azure/projects/justiceinnovationlab.tfvars` as well?

I've deleted all the resources except the resource group (as it contains the ACR) and the ACR itself. I did this by:

1. `terraform state list` to find list of things that `terraform destroy` will destroy
2. `terraform state rm azurerm_resource_group.jupyterhub` and `terraform state rm azurerm_container_registry.container_registry` to remove the entries for the ACR and the resource group from terraform's state, so it doesn't try to destroy them when we run terraform destroy
3. `cd terraform/azure` and `terraform destroy -var-file projects/justiceinnovationlab.tfvars`, and read the diff carefully before destroying

**Comment by yuvipanda** [comment]
I've removed the tfvars config as well.

**Pull request merged**
