### PR TITLE
Bumping OHW R image

### PR DESCRIPTION
**Pull request by abkfenris**
Hopefully this will fix some of the C library issues.

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by sgibson91** [comment]
I'm interested to know why our CI/CD didn't run on this PR.....

**Comment by abkfenris** [comment]
I told you I was good at breaking things.

**Comment by sgibson91** [comment]
Ok, at least _that_ CI/CD was successful!

**Comment by sgibson91** [comment]
But we should have also had a comment like this one: https://github.com/2i2c-org/infrastructure/pull/1629#issuecomment-1216194982

**Comment by abkfenris** [comment]
Hmm, when I previously made a PR with an image bump I got a comment: https://github.com/2i2c-org/infrastructure/pull/1599#issuecomment-1206153240

**Comment by sgibson91** [comment]
Yeah, I don't know why it wouldn't have triggered again. It doesn't show up here: https://github.com/2i2c-org/infrastructure/actions/workflows/deploy-hubs.yaml?query=event%3Apull_request And as far as I know, nothing has changed

**Comment by damianavila** [comment]
@sgibson91, do you think we should open an issue about this one ⬆️  or just consider it as a transient failure?

**Comment by sgibson91** [comment]
@damianavila I expect it was a transient failure. I believe githubstatus.com reported an Actions outage a little time after this so this was probably a precursor event.

**Pull request merged**
