### PR TITLE
openscapes: Use a bigger node to account for future event expected usage

### PR DESCRIPTION
**Pull request by GeorgianaElena**
For https://github.com/2i2c-org/infrastructure/issues/3217

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
## More users per node during events - yes!

I think its great to schedule so that we expect 8 users to fit on the node instead of just 2 for an event. During events we expect significant amounts of users, and I figure ending up with using around ~4-12 nodes is about right with regards to startup time considerations and ability to scale up/down in a more fine grained way to reduce cloud costs.

## Warning about just changing node selector

The guarantees and limits are generated based on the specific node size, a node with 4 times the size will have slightly more than 4 times the allocatable capacity overall I think.

If this was done in the other way, where we used requests(aka guarantees)/limits based on a larger node, adopted for a smaller node, we could end up with request of 51% or 101% of a nodes capacity etc, making us schedule ineffectively.

So in practice - we must be careful changing this without re-generating the list, but in this case its okay I think.

## Related discussions

- When the ~same resource request can be made on two node sizes, we currently only provide one option. Sometimes one is better than the other, so it would be good to be able to configure what requests should use what instance size. This is exactly what is changed here, we want to use the larger node for requests that could also be made on a smaller node during an event where we expect many users.
  https://github.com/2i2c-org/infrastructure/pull/3030#issuecomment-1706777492
- How many users per nodes are suitable?
  https://github.com/2i2c-org/infrastructure/issues/3177

**Review by consideRatio — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
> When the ~same resource request can be made on two node sizes, we currently only provide one option. Sometimes one is better than the other, so it would be good to be able to configure what requests should use what instance size. This is exactly what is changed here, we want to use the larger n

Ah, I get it! Thank you @consideRatio. I am feeling a bit more confident in what we want to achieve with node sharing and how, but it's lots of info to consider. But would love to have a central place where we document all these different scenarios.

**Comment by consideRatio** [comment]
>  But would love to have a central place where we document all these different scenarios.

I agree, I would have felt agency to write docs about this if we had clear guidance to go for. I've opened https://github.com/2i2c-org/infrastructure/issues/3177 to come up with preliminary guidance on how many users per node we may want to aim for. With such guidance we can not only document "this is complicated because..." but also "so here is a recommendation on what to do".

**Comment by GeorgianaElena** [comment]
Thank you @consideRatio! https://github.com/2i2c-org/infrastructure/issues/3177 seems like Q4 material 🚀 🚀 and something I'm looking forward to have <3

**Pull request merged**
