### PR TITLE
Allow restricting Callysto logins by domain

### PR DESCRIPTION
**Pull request by yuvipanda**
With Callysto, we do not use email addresses to try preserve user privacy a little. However, this makes restricting the domains users can login be a bit difficult - all our validation code validates the username itself, rather than any other attribute of it.

Here, we customize the authenticator to validate the email of the user, but not use that as the username. This allows us to enforce a list of domains (including wildcards) that can be allowed to login without having to set their emails to be their usernames.

Ref https://github.com/2i2c-org/infrastructure/issues/1678

### CODE REVIEW

**Comment by yuvipanda** [comment]
Would love to hear how we can upstream this as well, @GeorgianaElena :)

**Review by GeorgianaElena — APPROVED** [review]
This looks like the best solution! Thank you! 🚀

Do you think we should upstream this availability to allow based on domain, even on the claim being used is not `email`? I believe it might be useful for others?

**Comment by GeorgianaElena** [comment]
> Would love to hear how we can upstream this as well, @GeorgianaElena :)

Hhah, you were faster than me! Yes, I also believe this should be upstreamed 🚀

**Comment by yuvipanda** [comment]
@GeorgianaElena yesss we should! And please do open an issue :)

**Comment by GeorgianaElena** [comment]
Done https://github.com/jupyterhub/oauthenticator/issues/547 🚀

**Pull request merged**
