### PR TITLE
Switch to localized homepage template for UNITEFA-CONICET

### PR DESCRIPTION
**Pull request by jmunroe**
See #2870 .  Need to verify that the Spanish translation is at least passable before merging.

Note by Georgiana: The Spanish translation lives at https://github.com/2i2c-org/default-hub-homepage/commit/57f46d952691ec1af7e5692df17a525b1b98d1f9

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
@jmunroe, I left a couple of comments to https://github.com/2i2c-org/default-hub-homepage/commit/57f46d952691ec1af7e5692df17a525b1b98d1f9 to the best of my Spanish knowledge (which is not extensive :D ), but it looks good to me overall.

Nonetheless, I invite feedback from @damianavila to https://github.com/2i2c-org/default-hub-homepage/commit/57f46d952691ec1af7e5692df17a525b1b98d1f9.

Btw, I also temp deployed it to the staging hub and it looks pretty cool to me https://staging.2i2c.cloud (the change might get overridden soon though)

**Comment by yuvipanda** [comment]
@jmunroe @damianavila what do we do with this PR?

**Comment by jmunroe** [comment]
This will require additional work before it can be merged.  

Closing without merging.

**Comment by jmunroe** [comment]
The additional work of getting a professional translator (using Crowdin) has now been completed.  It think this PR is ready to be merged so it can be shown to the UNITEFA community champions

**Comment by jmunroe** [comment]
Tested deploy and get 500 errors. Rolled back the deployment and will try and resolve before merging.

**Comment by jmunroe** [comment]
There were issues with Crowdin messing up the Jinga2 templating. Fixed those and deploying now works as expected.

**Comment by jmunroe** [comment]
I've also changed the template login page for the staging site on this cluster as well.

I'll await a review before merging because I am touching two "sites" before merging.

**Review by sgibson91 — APPROVED** [review]

**Pull request closed without merging**
