### PR TITLE
Adds back: Allow restricting profiles & profile_options based on JupyterHub groups

### PR DESCRIPTION
**Pull request by consideRatio**
Reverts 2i2c-org/infrastructure#4045, practically adding the original PR back.

- I'll test this on pangeo-hubs staging and 2i2c-aws-us itcoocean where I think it didn't work before #4046 - TEST OK!
- I'll test this on pangeo-hubs prod - TEST OK!

### CODE REVIEW

**Comment by sgibson91** [comment]
I was waiting to open this, because now the deploy for https://github.com/2i2c-org/infrastructure/pull/4046 has been [cancelled](https://github.com/2i2c-org/infrastructure/actions/runs/9005975346). I might be able to re-run it though.

**Comment by consideRatio** [comment]
@sgibson91 ah =/

Don't re-run it, let's merge this instead - I've tested this successfully on staging and deploy to pangeo-hubs prod now to verify it works as well.

**Comment by sgibson91** [comment]
Ok, well I already cancelled and promoted the other job 😬

**Comment by sgibson91** [comment]
Pings come through too late

**Comment by consideRatio** [comment]
Ah no worries!

I'll go for a merge on this now to make it be in the pipeline next - the already running run won't get cancelled, only those that hasn't started are subject to being cancelled by merging

**Comment by sgibson91** [comment]
Yep

**Pull request merged**
