### PR TITLE
Keep at least one node up at all times for uwhackweeks

### PR DESCRIPTION
**Pull request by yuvipanda**
After making this change, I did:

```
jsonnet uwhackweeks.jsonnet > uwhackweeks.yaml
eksctl scale nodegroup --config-file=uwhackweeks.yaml
```

This brought up a node!

I authenticated via https://2i2c.awsapps.com/start#/,
and the AWS SSO setup.

Ref https://2i2c.freshdesk.com/a/tickets/100

### CODE REVIEW

**Comment by yuvipanda** [comment]
I've already deployed this.

**Review by consideRatio — APPROVED** [review]
LGTM I think, and given that it is already deployed and functional it feels kind of safe for me to approve!

**Comment by sgibson91** [comment]
Thank you @yuvipanda!

**Comment by damianavila** [comment]
Can we capture this process in some documentation bits?

For instance, it is important to highlight you are passing a config file to the `eksctl scale` command which is different from 
`eksctl create` command referenced here (https://infrastructure.2i2c.org/en/latest/howto/operate/new-cluster/aws.html#create-the-cluster) even when we use the same config file!
AFAIK (and I might miss something) the `scale` command is only looking at the scale-relevant pieces from that config file.

`eksctl` does NOT do cluster reconciliation as terraform yet, so this might confuse people, maybe?

**Comment by yuvipanda** [comment]
@damianavila yeah I agree that our eksctl process is not documented well at all. Needs fixing

**Comment by yuvipanda** [comment]
@damianavila follow-up docs in https://github.com/2i2c-org/infrastructure/pull/1138!

**Pull request merged**
