### PR TITLE
Enable selecting the environment to use for each machine profile on AWS carbonplan hubs

### PR DESCRIPTION
**Pull request by sgibson91**
fixes https://github.com/2i2c-org/infrastructure/issues/1640
fixes https://github.com/2i2c-org/infrastructure/issues/1641

### CODE REVIEW

**Comment by sgibson91** [comment]
I am hitting the following error in Actions atm

> Error: API rate limit exceeded for installation ID 10159873.

Will retry in ~1 hr

**Comment by damianavila** [comment]
> Will retry in ~1 h

I did not see a retry, am I correct about it?

**Comment by sgibson91** [comment]
I believe I did retry and got the same error. I think I need to push a new commit.

**Comment by sgibson91** [comment]
New commit worked

**Comment by sgibson91** [comment]
I am not sure why the bot is freaking out and constantly commenting now

**Review by GeorgianaElena — APPROVED** [review]
LGTM

**Comment by sgibson91** [comment]
Just awaiting confirmation from the carbonplan folks that this is appropriate before I merge

**Comment by sgibson91** [comment]
Got confirmation from Raphael in freshdesk, so will hit merge now

**Pull request merged**
