### PR TITLE
Cull pods that run for longer than 7 days

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://github.com/2i2c-org/infrastructure/issues/3015

### CODE REVIEW

**Review by damianavila — APPROVED** [review]

**Comment by consideRatio** [comment]
I agree with this change, but i dont think we should introduce it silently. I think this is something the QCL community should be informed about at least as they have in the past had longer time running calculations on a single node.

I think it could make sense to notify all community champions about this, and i figure this config is us influencing the user env - so it should be documented somewhere for them.

I opened #3017 about communication in situations like this among other things as i've felt that I lack agency on how to communicate a change influencing users if we've decided its the right thing to do.

For this change, i suggest:
- we communicate that we planning this change at a certain date, referencing docs we've written explaining the default of having a max age.
- invite users to opt-out or get another max-age
- do the change

**Comment by yuvipanda** [comment]
Thanks @consideRatio.

I don't think I've the capacity to work on communicating at this point, and am not sure who does. So I'm going to unassign this to myself as I don't think I can take this to completion.

**Comment by jmunroe** [comment]
We just received feedback from QCL (https://2i2c.freshdesk.com/a/tickets/972) on this:

> 7 days would be excellent for us. Will this be the same limit as the timeout for a disconnected session (that still has processes running)?

I think the answer to the question is "yes" but I welcome corrections if there is subtly on this.

In any case I think this response unblocks this PR!

**Review by consideRatio — APPROVED** [review]
I think a lot of the long running jobs observed was caused by the KubeSpawner bug in 6.0.0 that has been fixed and cleaned up. With that in mind, I no longer expect this to be as breaking as I thought when seeing several long lived pods.

I'll push a commit to update the docs currently saying there isn't a max lifetime limit to say that there is one of 7 days: https://docs.2i2c.org/admin/howto/control-user-server/#stop-user-servers-after-inactivity

**Comment by consideRatio** [comment]
@jmunroe i pinged you for review by mistake. I meant to assign to for attribution for work done!

**Pull request merged**
