### PR TITLE
openscapes: Mount homedir for rocker profile under /home/rstudio

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/2i2c-org/infrastructure/issues/3242

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
Thanks @yuvipanda!

**Review by damianavila — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
Since https://github.com/2i2c-org/infrastructure/pull/3347 got merged, I believe this can now be closed. Please reopen if you disagree.

**Comment by yuvipanda** [comment]
I think we should still merge this, because `$HOME` and stuff is currently set wrongly.

**Comment by yuvipanda** [comment]
I got the go ahead for this from @betolink, will deploy this today

**Pull request merged**
