### PR TITLE
linked-earth: switch to e2-highmem instances and shared nodes

### PR DESCRIPTION
**Pull request by consideRatio**
Already deployed, works!

### CODE REVIEW

**Comment by yuvipanda** [comment]
@consideRatio at least last time I checked, I think the e2- nodes are actually slightly more expensive because they don't have committed use discounts (https://github.com/berkeley-dsep-infra/datahub/issues/1354). Do you know if that has changed?

**Review by yuvipanda — APPROVED** [review]
I don't think the e2- question should block this PR!

**Comment by consideRatio** [comment]
> @consideRatio at least last time I checked, I think the e2- nodes are actually slightly more expensive because they don't have committed use discounts (https://github.com/berkeley-dsep-infra/datahub/issues/1354). Do you know if that has changed?

It seems [sustained use discounts are not provided for E2](https://cloud.google.com/compute/docs/sustained-use-discounts), which is what we may benefit from, as compared to comitted use. Sustained use is especially relevant for the core nodes I guess.

Doh!

**Comment by yuvipanda** [comment]
@consideRatio yep! sustained use discounts is what I meant. So without that, e2- nodes actually end up slightly more expensive for us, not just for core nodes but for *all* kinds of nodes - as sustained use discount is not on a per-VM basis but a per-type-of-VM basis, based on my understanding of https://cloud.google.com/compute/docs/sustained-use-discounts. So it is benificial to both notebook and core nodes pretty heavily.

**Pull request merged**
