### PR TITLE
Add a new nasa-cryo persistent bucket for staging and prod hubs

### LINKED ISSUE #2893: Create a persistent bucket for nasa-cryo
- Requested name: `s3://nasa-cryo`
Update: actual name will be `s3://nasa-cryo-persistent` because by convention, we are adding as suffix the id of the bucket from the config.

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Fixes #2893

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
Thanks @sgibson91! I've just ran `terraform plan` and unfortunately I'm seeing some errors:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
 <= read (data resources)

Terraform planned the following actions, but then encountered a problem:

  # data.aws_iam_policy_document.bucket_access["prod.persistent"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
              + (known after apply),
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-prod",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["prod.scratch"] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:s3:::nasa-cryo-scratch",
              + "arn:aws:s3:::nasa-cryo-scratch/*",
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-prod",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["staging.persistent-staging"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
              + (known after apply),
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-staging",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["staging.scratch-staging"] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:s3:::nasa-cryo-scratch-staging",
              + "arn:aws:s3:::nasa-cryo-scratch-staging/*",
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-staging",
                ]
              + type        = "AWS"
            }
        }
    }

  # aws_iam_user_policy.continuous_deployer will be updated in-place
  ~ resource "aws_iam_user_policy" "continuous_deployer" {
        id     = "hub-continuous-deployer:eks-readonly"
        name   = "eks-readonly"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Resource = "*" -> "arn:aws:eks:us-west-2:574251165169:cluster/nasa-cryo"
                        # (2 unchanged attributes hidden)
                    },
                ]
                # (1 unchanged attribute hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket.user_buckets["persistent"] will be created
  + resource "aws_s3_bucket" "user_buckets" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "nasa-cryo-persistent"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # aws_s3_bucket.user_buckets["persistent-staging"] will be created
  + resource "aws_s3_bucket" "user_buckets" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "nasa-cryo-persistent-staging"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # aws_s3_bucket_policy.user_bucket_access["prod.persistent"] will be created
  + resource "aws_s3_bucket_policy" "user_bucket_access" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # aws_s3_bucket_policy.user_bucket_access["prod.scratch"] will be updated in-place
  ~ resource "aws_s3_bucket_policy" "user_bucket_access" {
        id     = "nasa-cryo-scratch"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "s3:*"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::574251165169:role/nasa-cryo-prod"
                        }
                      - Resource  = [
                          - "arn:aws:s3:::nasa-cryo-scratch/*",
                          - "arn:aws:s3:::nasa-cryo-scratch",
                        ]
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket_policy.user_bucket_access["staging.persistent-staging"] will be created
  + resource "aws_s3_bucket_policy" "user_bucket_access" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # aws_s3_bucket_policy.user_bucket_access["staging.scratch-staging"] will be updated in-place
  ~ resource "aws_s3_bucket_policy" "user_bucket_access" {
        id     = "nasa-cryo-scratch-staging"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "s3:*"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::574251165169:role/nasa-cryo-staging"
                        }
                      - Resource  = [
                          - "arn:aws:s3:::nasa-cryo-scratch-staging/*",
                          - "arn:aws:s3:::nasa-cryo-scratch-staging",
                        ]
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 4 to add, 3 to change, 0 to destroy.
╷
│ Error: Insufficient rule blocks
│ 
│   on buckets.tf line 7, in resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry":
│    7: resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry" {
│ 
│ At least 1 "rule" blocks are required.
╵
╷
│ Error: Insufficient rule blocks
│ 
│   on buckets.tf line 7, in resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry":
│    7: resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry" {
│ 
│ At least 1 "rule" blocks are required.
╵

```

**Comment by sgibson91** [comment]
Here are some docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration

Do we have `lifecycle_rule` set? If so, it looks like it might need to be changed to this `aws_s3_bucket_lifecycle_configuration` resource instead

**Comment by GeorgianaElena** [comment]
@sgibson91, I think the issue is that [now `rule` is a required field](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#argument-reference). And for persistent buckets, we're just specifying the `aws_s3_bucket_lifecycle_configuration` resource, but with no rules.

I added https://github.com/2i2c-org/infrastructure/pull/2894/commits/66f6fbebc17f05d55dd7c9bb307ae591c4c9365a that adds a rule for all types of buckets, but for the persistent ones, the rule is just disabled.

The `terraform plan` output is now:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_iam_policy_document.bucket_access["prod.persistent"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
              + (known after apply),
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-prod",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["prod.scratch"] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:s3:::nasa-cryo-scratch",
              + "arn:aws:s3:::nasa-cryo-scratch/*",
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-prod",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["staging.persistent-staging"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
              + (known after apply),
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-staging",
                ]
              + type        = "AWS"
            }
        }
    }

  # data.aws_iam_policy_document.bucket_access["staging.scratch-staging"] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_iam_policy_document" "bucket_access" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:s3:::nasa-cryo-scratch-staging",
              + "arn:aws:s3:::nasa-cryo-scratch-staging/*",
            ]

          + principals {
              + identifiers = [
                  + "arn:aws:iam::574251165169:role/nasa-cryo-staging",
                ]
              + type        = "AWS"
            }
        }
    }

  # aws_iam_user_policy.continuous_deployer will be updated in-place
  ~ resource "aws_iam_user_policy" "continuous_deployer" {
        id     = "hub-continuous-deployer:eks-readonly"
        name   = "eks-readonly"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Resource = "*" -> "arn:aws:eks:us-west-2:574251165169:cluster/nasa-cryo"
                        # (2 unchanged attributes hidden)
                    },
                ]
                # (1 unchanged attribute hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket.user_buckets["persistent"] will be created
  + resource "aws_s3_bucket" "user_buckets" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "nasa-cryo-persistent"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # aws_s3_bucket.user_buckets["persistent-staging"] will be created
  + resource "aws_s3_bucket" "user_buckets" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "nasa-cryo-persistent-staging"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # aws_s3_bucket_lifecycle_configuration.user_bucket_expiry["persistent"] will be created
  + resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry" {
      + bucket = "nasa-cryo-persistent"
      + id     = (known after apply)

      + rule {
          + id     = "delete-after-expiry"
          + status = "Disabled"

          + expiration {
              + days                         = 0
              + expired_object_delete_marker = (known after apply)
            }
        }
    }

  # aws_s3_bucket_lifecycle_configuration.user_bucket_expiry["persistent-staging"] will be created
  + resource "aws_s3_bucket_lifecycle_configuration" "user_bucket_expiry" {
      + bucket = "nasa-cryo-persistent-staging"
      + id     = (known after apply)

      + rule {
          + id     = "delete-after-expiry"
          + status = "Disabled"

          + expiration {
              + days                         = 0
              + expired_object_delete_marker = (known after apply)
            }
        }
    }

  # aws_s3_bucket_policy.user_bucket_access["prod.persistent"] will be created
  + resource "aws_s3_bucket_policy" "user_bucket_access" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # aws_s3_bucket_policy.user_bucket_access["prod.scratch"] will be updated in-place
  ~ resource "aws_s3_bucket_policy" "user_bucket_access" {
        id     = "nasa-cryo-scratch"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "s3:*"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::574251165169:role/nasa-cryo-prod"
                        }
                      - Resource  = [
                          - "arn:aws:s3:::nasa-cryo-scratch/*",
                          - "arn:aws:s3:::nasa-cryo-scratch",
                        ]
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket_policy.user_bucket_access["staging.persistent-staging"] will be created
  + resource "aws_s3_bucket_policy" "user_bucket_access" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # aws_s3_bucket_policy.user_bucket_access["staging.scratch-staging"] will be updated in-place
  ~ resource "aws_s3_bucket_policy" "user_bucket_access" {
        id     = "nasa-cryo-scratch-staging"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "s3:*"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::574251165169:role/nasa-cryo-staging"
                        }
                      - Resource  = [
                          - "arn:aws:s3:::nasa-cryo-scratch-staging/*",
                          - "arn:aws:s3:::nasa-cryo-scratch-staging",
                        ]
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 6 to add, 3 to change, 0 to destroy.

```

@sgibson91, what do you think about this. Does the change and terraform plan make sense to you?

**Comment by sgibson91** [comment]
@GeorgianaElena LGTM!

**Pull request merged**
