### PR TITLE
[Catalyst-Africa] New lot of hubs (aibst, bhki and bon)

### PR DESCRIPTION
**Pull request by AIDEA775**
ref: https://github.com/2i2c-org/infrastructure/issues/3822 (aibst)
url: https://aibst.af.catalystproject.2i2c.cloud/

ref: https://github.com/2i2c-org/infrastructure/issues/3821 (bhki)
url: https://bhki.af.catalystproject.2i2c.cloud/

ref: https://github.com/2i2c-org/infrastructure/issues/3820 (bon)
url: https://bon.af.catalystproject.2i2c.cloud/

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
Looks great, what a flow of hub turnups!

**Comment by yuvipanda** [comment]
This is *great work*, @AIDEA775!

**Comment by yuvipanda** [comment]
@AIDEA775 anything else you need to get these merged?

**Comment by yuvipanda** [comment]
@AIDEA775 ah, I think it's ok to merge the PR without waiting for that - we can leave the *issue* open until the community approves, but the PR can be merged as soon as it gets working.

I'll try to codify this as part of the new hub process as well. Thanks!

**Pull request merged**
