### PR TITLE
Split up Authentication docs into individual providers

### PR DESCRIPTION
**Pull request by sgibson91**
I find it difficult to follow docs when they become too long on the page, especially when they are tackling multiple topics, and I've begun to struggle with our Authentication docs. Therefore, this PR splits out each auth provider into their own file, making the rendered webpages shorter and easier to parse.

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
YES! 🚀

**Comment by sgibson91** [comment]
Thanks @GeorgianaElena! Do you want to merge https://github.com/2i2c-org/infrastructure/pull/1583 first? I suspect a conflict will arise once one of these two is merged

**Comment by GeorgianaElena** [comment]
I just merged that! Sorry for the conflict-related work that I've generated 😬

**Comment by sgibson91** [comment]
It's ok, no worries!

**Pull request merged**
