### PR TITLE
basehub: update jupyterhub chart from 3.2.1 to 3.3.7 (Scheduled for 9nd April)

### PR DESCRIPTION
**Pull request by consideRatio**
This update brings in jupyterhub 4.1.0 and oauthenticator 16.3.0.

## Two bugfixes upstream

This early adoption of z2jh's new release led to catching two bugs.

- First 3.3.0 failed because of a pycurl regression (observed when using oauthenticator to sign in)
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3366
- Then 3.3.1 failed because of a iptables regression (observed when starting a user pod)
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3368

## Compatibility fix in jupyterhub-configurator

- [x] The jupyterhub-configurator's web-server made use of HubOAuthenticator that now requires xsrf tokens when receiving javascript fetch requests. This is resolved by https://github.com/yuvipanda/jupyterhub-configurator/pull/19 which is backported to an old enough commit in a branch we now build from. This branch can be adopted without introducing breaking changes.
- [x] Closes https://github.com/2i2c-org/infrastructure/issues/3197, let's not try to migrate to use the latest jupyterhub-configurator commit as it has introduced breaking changes that we would need to migrate config to handle.

## About JupyterHub 4.1.1 - 4.1.5 releases

Several (all?) of the issues patched related to `jupyterhub` code executed in the user servers, which are unaffected by this PRs upgrade of the server side part of jupyterhub.

- In 4.1.1, https://github.com/jupyterhub/jupyterhub/pull/4745
- In 4.1.2, https://github.com/jupyterhub/jupyterhub/pull/4750
- In 4.1.3, https://github.com/jupyterhub/jupyterhub/pull/4753
- In 4.1.4, https://github.com/jupyterhub/jupyterhub/pull/4759
- In 4.1.5, https://github.com/jupyterhub/jupyterhub/pull/4771

## Verifications

- [x] jupyterhub-configurator works
- [x] rstudio works
- [x] nbgitpuller works (nbgitpuller 1.2.1+ is required if jupyterhub 4.1 is used in the user env)
- [x] jupyter-resource-usage works
- [x] jupyter-remote-desktop-proxy works (2.0.0+ is required if jupyterhub 4.1 is used in the user env)
- [x] jupyter notebook 6
- [x] jupyter notebook 7 (jupyter_server based, like jupyter lab)

## Related

- z2jh changelog: https://z2jh.jupyter.org/en/stable/changelog.html
- jupyterhub changelog: https://jupyterhub.readthedocs.io/en/stable/reference/changelog.html
- oauthenticator changelog: https://oauthenticator.readthedocs.io/en/latest/reference/changelog.html

### CODE REVIEW

**Comment by consideRatio** [comment]
z2jh 3.3.0 is broken because pycurl is broken due to a regression in a patch release, working to fix it now.

**Review by yuvipanda — APPROVED** [review]
Test in a staging environment and then this is good to go!

**Comment by consideRatio** [comment]
Okay, two z2jh patch releases later things work it seems!

Will merge tomorrow when I'm starting my workday

**Comment by consideRatio** [comment]
@yuvipanda I'm getting pulled into needing to understand how jupyterhub-configurator works etc since its broken against jupyterhub 4.1.0 - likely due to CORS related changes.

I'd like to bite the bullet and catch up with misc maintenance:
- https://github.com/2i2c-org/infrastructure/issues/3197
- review stale PRs in https://github.com/yuvipanda/jupyterhub-configurator/pulls
- get it jupyterhub 4.1.0 compatible
- maybe make a 1.0.0 release to PyPI because its notable work to pin and communicate about commits compared to do releases with changelogs etc

Are you OK with granting me maintainer rights and going for it quite swiftly?

**Comment by yuvipanda** [comment]
@consideRatio I've added you as maintainer. However, there are no users of that outside of 2i2c (especially after it was taken out of tljh), and it is an architectural dead end. I think it's ok to do the work that unblocks z2jh upgrades, but i don't think it should have any other work done on it at all.

I've closed or merged PRs as appropriate.

**Comment by yuvipanda** [comment]
I'd also think it's appropriate to rollback `jupyterhub-configurator` to the commit that was known good and worked here, do whatever fix is needed for 4.1, and just get that going.

**Review by yuvipanda — CHANGES_REQUESTED** [review]
Given the xsrf changes seem to be slightly bumpy, I suggest we hold off this for a week to let things shake out.

**Comment by consideRatio** [comment]
I'm planning this to be deployed next tuesday - 2nd April.

**Comment by yuvipanda** [comment]
That schedule looks good to me, @consideRatio. I'd like at least the following things to be tested before this is deployed everywhere:

- [ ] nbgitpuller (server extension with its own UI)
- [ ] RStudio (complex proxied app)
- [ ] jupyter-remote-desktop-proxy (simpler proxied app, with its own server extension)
- [ ] Make sure the resource usage display in the status bar of JupyterLab works (pure API extension)
- [ ] Classic Notebook (because I don't fully know how this does xsrf, and how it interacts with possible changes to jupyterhub-singleuser)

This should give us enough confidence that most things will work.

**Comment by consideRatio** [comment]
I agree @yuvipanda, note though that I expect a lot of these issues to arise independent on what is done server-side, but in the user images using a modern jupyterhub version.

**Comment by consideRatio** [comment]
@yuvipanda I've verified that a server-side change doesn't cause issues in any of the things you listed.

---

Beyond this because its related, I've considered the user environments. I've concluded that jupyterhub 4.1.4, nbgitpuller 1.2.1, and jupyter-remote-desktop-proxy 2.0.0, jupyter-resource-usage 1.0.2 (no patch needed), and utoronto's classical UI from notebook 6, Lab UI, and RStudio UI works when jupyterhub-singleuser 4.1.4 is used in the user environment - use of jupyterhub 4.0 or 4.1 server side doesn't change this.

- jupyter/docker-stacks latest published images have jupyterhub 4.1.4
- pangeo/pangeo-docker-images latest tagged image has jupyterhub 4.0.2, and will when release is made go straight to 4.1.4 with nbgitpuller 1.2.1 as its part of the master branch already.
- rocker/binder images have jupyterhub 4.1.3 currently which makes rstudio work

**Comment by yuvipanda** [comment]
@consideRatio thanks for doing that. My suggestion is to do this next week, given we still have a bunch of things that we had committed to this sprint not done yet. We can schedule this during the sprint planning meeting for the next one.

**Comment by consideRatio** [comment]
@yuvipanda rescheduled to 9th april!

**Comment by damianavila** [comment]
Ask @GeorgianaElena to spend some cycles on this one next week.

**Pull request merged**
