### PR TITLE
Remove uwhackweeks.2i2c.cloud

### PR DESCRIPTION
**Pull request by GeorgianaElena**
- Removes config of the prod uwhackweeks.2i2c.cloud hub
- I kept the staging to help with testing the snowex one. Is this ok?
- I believe we also need to remove the scratch bucket for this hub, right? (we should add this to the decommission steps if so) https://github.com/2i2c-org/infrastructure/blob/16bd879f40c0cc7f81da9629c98368c80cac42de/terraform/aws/projects/uwhackweeks.tfvars#L11-L13

Manual todos:
- [ ] delete home dirs
- [ ] delete github oauth app
- [ ] Remove the hub deployment
      - `helm --namespace uwhackweeks delete prod`
      - `kubectl delete namespace prod`

Ref: https://github.com/2i2c-org/infrastructure/issues/1336

### CODE REVIEW

**Review by yuvipanda — APPROVED** [review]
Yay! We'll also need to delete the home directories tho. I think keeping the staging hub is fine. I think what was at 'uwhackweeks.2i2c.cloud' is really the ICESat hackweek hub, and we'll run more of these in the future here.

**Comment by GeorgianaElena** [comment]
I'm currently deleting the home dirs of the users

**Comment by damianavila** [comment]
> I'm currently deleting the home dirs of the users

@GeorgianaElena, can you confirm when this is done so I push this one to the "Done" column? Thanks!

**Comment by GeorgianaElena** [comment]
Home dirs are gone 🚀

**Pull request merged**
