### PR TITLE
New R image build to fix deployment error

### PR DESCRIPTION
**Pull request by emiliom**
Added `jsonschema-with-format-nongpl` to the conda environment.

See discussions in https://github.com/2i2c-org/infrastructure/pull/2252#issuecomment-1444887522

cc @yuvipanda

### CODE REVIEW

**Comment by emiliom** [comment]
Thanks! I'll test it out when it's ready. :crossed_fingers:

**Comment by emiliom** [comment]
Well, that was quick :cry: : https://github.com/2i2c-org/infrastructure/actions/runs/4268087896/jobs/7430336686#step:3:268

**Comment by yuvipanda** [comment]
@emiliom let me try that again, that looks like an unrelated error. have restarated it

**Comment by yuvipanda** [comment]
@emiliom the deploy succeeded!

**Comment by emiliom** [comment]
Thank you!! I've tried it out, and both Python and R images work!

Again, thanks so much.

**Pull request merged**
