### PR TITLE
Enable pulling private GitHub repos for Neurohackademy

### PR DESCRIPTION
**Pull request by sgibson91**
Following instructions in #2849 as an alternative for authenticated static sites

new hub issue: #2681

I reused the same GitHub App that I had previously set up for the static site and is already installed on the appropriate repo.

### CODE REVIEW

**Review by pnasrat — APPROVED** [review]
LGTM

**Comment by sgibson91** [comment]
I am holding off on merging this as nbgitpuller is returning a 128 error status

**Comment by sgibson91** [comment]
Booooo! (Let me push the commit that generated this)

```
2023-07-21T16:57:09Z [Warning] Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/8b096c8a-84e4-4bee-b35c-18e9025c7c4e/volume-subpaths/files/notebook/2" to rootfs at "/srv/conda/envs/notebook/etc/gitconfig/github-app-private-key.pem": open o_path procfd: open /run/containerd/io.containerd.runtime.v2.task/k8s.io/notebook/rootfs/srv/conda/envs/notebook/etc/gitconfig/github-app-private-key.pem: not a directory: unknown
```

**Comment by sgibson91** [comment]
No wait, I think I've just done the wrong thing.. hang on

**Comment by sgibson91** [comment]
Cracked it!

**Pull request merged**
