### PR TITLE
set up for a HHMI deploy re: #3332

### PR DESCRIPTION
**Pull request by jmunroe**

### CODE REVIEW

**Comment by jmunroe** [comment]
This will go through additional iterations after the meeting tomorrow afternoon with HHMI.

I've already tested and deployed.  To keep the changes persistent, I feel I should self-merge this.  Is that the correct policy? (I think so -- but I don't want to overstep)

**Review by GeorgianaElena — APPROVED** [review]
@jmunroe, we have the self-merging policy defined at https://infrastructure.2i2c.org/contributing/code-review/#self-merging-as-a-2i2c-engineer.

I suggest documenting this particular case there also if you believe qualifies.

Also, this PR looks good to me 🚀

**Comment by consideRatio** [comment]
Nice @jmunroe!!!

Is this closing #3332 btw? Then you can add a `fixes #3332` or `closes #3332` in the PR description to have it close that issue. If you put it there instead of in the title, there will be a clickable link as well btw.

**Comment by jmunroe** [comment]
> @jmunroe, we have the self-merging policy defined at https://infrastructure.2i2c.org/contributing/code-review/#self-merging-as-a-2i2c-engineer.
> 
> I suggest documenting this particular case there also if you believe qualifies.
> 
> Also, this PR looks good to me 🚀

Thanks @GeorgianaElena .  I think the changes in this PR go beyond the guidelines for a self-merge so I will leave as they are.

**Comment by jmunroe** [comment]
> Nice @jmunroe!!!
> 
> Is this closing #3332 btw? Then you can add a `fixes #3332` or `closes #3332` in the PR description to have it close that issue. If you put it there instead of in the title, there will be a clickable link as well btw.

Aha! I knew there was something like that but didn't know that the keywords were "fixes" and "closes". Thanks!

**Pull request merged**
