### PR TITLE
NASA-Veda cluster and hub

### LINKED ISSUE #2017: [Request deployment] New Hub: NASA VEDA Hub
### Important dates

- **Target start date**: 2023-01-24
- **Required start date**: 2023-02-01

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@abarciauskas-bgse
@freitagb
@j08lue
@rezuma

### [GitHub Auth only] How would you like to manage your users?

Allowing members of specific GitHub team(s): `@veda-analytics-access/all-users`

### [GitHub Teams Auth only] Profile restriction based on team membership

> No restriction for now, thanks - @veda-analytics-access/all-users should get the one machine size we have. We might want to add more in the future, though, if that is okay.

### Hub logo image URL

pending

### Hub logo website URL

https://www.earthdata.nasa.gov/esds/veda

### Hub user image GitHub repository

> 2i2c default / pangeo-notebook https://github.com/pangeo-data/pangeo-docker-images/tree/master/pangeo-notebook

### Hub user image tag and name

> 2i2c default / latest tagged release - at the time of writing pangeo/pangeo-notebook:2023.01.04

### Extra features you'd like to enable

- [x] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

### (Optional) Preferred cloud provider

> [Science Managed Cloud Environment (SMCE)](https://www.nccs.nasa.gov/systems/SMCE) - a managed Amazon Web Service (AWS) based infrastructure for NASA funded projects

> We had a coordinating discussion between 2i2c and NASA earlier this week and found a working arrangement. SMCE creates the AWS organization and 2i2c gets accounts with full access, as I recall.

### (Optional) Billing and Cloud account

To be provided by SMCE @rezuma

### Other relevant information to the features above

_No response_

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR: https://github.com/2i2c-org/infrastructure/pull/2083
- [ ] 5. Administrators able to log on -> Hub now in steady-state

### PR DESCRIPTION
**Pull request by yuvipanda**
- Adds more restrictions to the AWS IAM CI/CD user, to only have permissions to this
  *specific* EKS cluster (rather than to all EKS clusters). 
- Add encrypted CI/CD user credentials here
- Add documentation on how users can ssh into nodes, both for AWS & GCP. Does not
  require manually managing SSH keys.

Currently waiting on a MFA exception for this IAM user so we can deploy from here.

Closes #2017

### CODE REVIEW

**Comment by sgibson91** [comment]
I love these docs Yuvi! ❤️

**Review by consideRatio — APPROVED** [review]
Excellent docs!

**Review by consideRatio — CHANGES_REQUESTED** [review]
I approved this but now notice that cluster.yaml for example is missing which causes failures in our CI systems if this is merged as it is - so I'm revoking the approval.

What has been added so far looks great though!

**Comment by GeorgianaElena** [comment]
I've added a commit that adds a minimal `cluster.yaml` so we can get this merged and then deploy de hubs, but the CI doesn't run because of the API rate limit :/

**Review by consideRatio — APPROVED** [review]
@GeorgianaElena go for it!

**Comment by GeorgianaElena** [comment]
@consideRatio, @sgibson91, I believe I will go ahead and add the appropriate files for the hub to this PR and then merge it, according to https://github.com/2i2c-org/leads/issues/91#issuecomment-1404743849. Does this plan sound ok to you too?

**Comment by sgibson91** [comment]
> @consideRatio, @sgibson91, I believe I will go ahead and add the appropriate files for the hub to this PR and then merge it, according to [2i2c-org/leads#91 (comment)](https://github.com/2i2c-org/leads/issues/91#issuecomment-1404743849). Does this plan sound ok to you too?

Yes. I quickly gave up on trying to do separate terraform/cluster and then hub PRs, usually because the tf PR didn't get merged in time, and rebasing the other branch became a mess. Much simpler to do it all in one.

**Comment by sgibson91** [comment]
I think you will also need to add the cluster to the "deploy grafana dashboards" workflow file too?

**Comment by GeorgianaElena** [comment]
Thanks @sgibson91! I have also deployed everything here and seems to be looking and spawing ok.

**Comment by yuvipanda** [comment]
Yes thank you for taking this pr over @GeorgianaElena

**Review by sgibson91 — APPROVED** [review]

**Pull request merged**
