### PR TITLE
Update ohw.values.yaml, Python & R images + some text & links

### PR DESCRIPTION
**Pull request by emiliom**
Updates for 2024 OHW24-in-Spanish events.

- Update Python & R images
- Change image selection text to Spanish
- Switch logo, url and funding acknowledgment to OHW24-in-Spanish events

xref #4883

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by emiliom** [comment]
The [deployment failed](https://github.com/2i2c-org/infrastructure/actions/runs/11167078112). What's the next step to identify the problem?

**Comment by sgibson91** [comment]
I've rerun the CI, but otherwise I'll have to deploy locally. I'll do that tomorrow if needed.

**Comment by emiliom** [comment]
Thanks, but it failed again. Hopefully your local deployment will fix things.

**Comment by emiliom** [comment]
@sgibson91 Crossing fingers that you'll be able to sort out the problem and deploy this update .... Thanks again!

**Comment by sgibson91** [comment]
Local deploy went fine. CI was timing out testing the dask-staging hub on the same cluster

**Comment by emiliom** [comment]
Wonderful, thank you! I can see that the new deployment is up. Looks good.

**Pull request merged**
