### PR TITLE
Add opinionated dependabot config

### PR DESCRIPTION
**Pull request by sgibson91**
This adds a configuration file to enable dependency bumps for our `docs` folder via dependabot. In #1012, folks were concerned about noise and so this is a really opinionated config and those trade-offs are described in comments at the top and throughout the config file.

There will be an initial flurry of PRs when we merge this and dependabot stabilises, after that it should only run weekly on Mondays. I'm happy to take on the work of reviewing/merging those initial PRs. One reason we chose the `docs` folder is because readthedocs builds/tests our docs in every PR, and so we will quickly be able to tell if we run into issues.

### CODE REVIEW

**Review by choldgraf — APPROVED** [review]
This looks good to me - let's give it a shot!

Just a note that I discovered you can tell Dependabot to manually run. Just go to the dependabot tab of the repo (on the book theme it is https://github.com/executablebooks/sphinx-book-theme/network/updates) and you can select subsets of ecosystems to run on.

This is particularly useful to get past that initial flurry of PRs (since the bot will only keep 5 open at a time)

**Comment by sgibson91** [comment]
@choldgraf Good tip! Unfortunately, that link is a 404 for me?

**Comment by choldgraf** [comment]
Ah it may only be available for repo admins. Try the same url pattern with our repo?

**Comment by sgibson91** [comment]
Yeah I found it. But what I'm confused about is that there is seemingly no way to navigate there via the UI - you have to go straight to the URL. The left-hand-side options also look like the old settings menu style. Maybe they're in the middle of a refresh and it'll get ported over soon?

**Comment by choldgraf** [comment]
I believe you can get there from the `dependencies` link in the dropdown menu for the repo to the right:

image

then there's a dependabot tab on the next page

**Comment by sgibson91** [comment]
Oof, all that stuff that used to be findable along the top and now they've hidden. Thanks GitHub 👍🏻 

Complaining aside, thank you for walking me through that

**Comment by choldgraf** [comment]
it took me a few tries to find it as well haha, agreed

**Pull request merged**
