### PR TITLE
Setup gh-scoped-creds on pangeo hub

### PR DESCRIPTION
**Pull request by yuvipanda**
Also adds docs on how to do this!

https://github.com/pangeo-data/pangeo-docker-images/pull/305 adds
the required package to the pangeo docker image.

See https://github.com/2i2c-org/docs/pull/138#discussion_r848808092
for more discussion

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
What a great feature! 🚀 Thanks @yuvipanda for creating this!

**Comment by yuvipanda** [comment]
Thanks, @GeorgianaElena!

**Comment by damianavila** [comment]
> We should update the service docs as well so people discover this!

I think @yuvipanda already did that on this PR: https://github.com/rabernat/2i2c-docs/pull/1

**Comment by damianavila** [comment]
Added a new upstream issue ⬆️ so we can track the upstream work.

**Comment by yuvipanda** [comment]
Thanks a lot, @damianavila

**Pull request merged**
