### PR TITLE
Prevent unencrypted files from being checked in

### PR DESCRIPTION
**Pull request by yuvipanda**
I wrote https://github.com/yuvipanda/pre-commit-hook-ensure-sops
to prevent possible unencrypted files from being checked-in! This
reduces need to keep unencrypted files on disk at rest in our
local checkouts as well.

Any file with the word 'secret' in its path will be checked to
make sure it is encrypted with sops. Exclusions will have to
be explicitly listed in our .pre-commit-config.yaml file - I'd
rather we be over-aggressive with this than not, given the
possible dire consequences of a credential leak.

I moved the sops encrypted ssh keys we use for our eksctl / kops
clusters into a directory named 'secret' so they are also checked

### CODE REVIEW

**Comment by yuvipanda** [comment]
I also want to get the pre-commit hook itself moved into the 2i2c org - https://github.com/yuvipanda/pre-commit-hook-ensure-sops. What do folks think?

**Comment by choldgraf** [comment]
I think this is a clever idea to keep us from accidentally committing something we don't want to!

**Review by sgibson91 — APPROVED** [review]
🎉🎉🎉

**Comment by yuvipanda** [comment]
Thanks, @sgibson91!

**Pull request merged**
