### PR TITLE
Update cryptonono's location

### PR DESCRIPTION
**Pull request by GeorgianaElena**
The repo has moved under a new account: https://github.com/cryptnono/cryptnono (see https://github.com/cryptnono/cryptnono/pull/25#issuecomment-1889099710)

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by sgibson91** [comment]
Ha, maybe a premature approval there :D

**Comment by sgibson91** [comment]
From the error message, I think it's still trying to pull the old repo. So it may be a "merge and hope" scenario, due to how the repo is getting checked out in CI.

**Comment by sgibson91** [comment]
Does it work locally? I'm not sure that we cache anything helm chart related in CI. I think it's likely running as if on master and not executing the change

**Comment by sgibson91** [comment]
We may also want to consider this PR https://github.com/2i2c-org/infrastructure/pull/3482/files

**Comment by GeorgianaElena** [comment]
Hmm, I just checked and same happens locally 🤔

**Comment by sgibson91** [comment]
This website is a 404 https://cryptnono.github.io/

**Comment by sgibson91** [comment]
Seems the repo is still trying to deploy to yuvipanda.github.io/cryptnono but that is now also a 404

https://github.com/cryptnono/cryptnono/deployments/github-pages

**Comment by GeorgianaElena** [comment]
> This website is a 404 https://cryptnono.github.io/cryptnono/

I believe that is acceptable, but https://cryptnono.github.io/cryptnono/cryptnono-0.3.1-0.dev.git.107.heb504bc.tgz has appropriate resource.

> Seems the repo is still trying to deploy to yuvipanda.github.io/cryptnono but that is now also a 404

So maybe the workflows need updating?

**Comment by sgibson91** [comment]
> So maybe the workflows need updating?

But that's what this PR is doing, which leads me back to my original assumption that we hit merge and hope?

**Comment by yuvipanda** [comment]
Sorry, I moved it for this blog post (https://github.com/2i2c-org/2i2c-org.github.io/pull/205) but somehow thought github will also do redirects for the generated gh-pages stuff (not just the repo).

I'm going to merge this to unblock folks.

**Comment by GeorgianaElena** [comment]
So this is failing on the main branch as well :( I've opened https://github.com/cryptnono/cryptnono/pull/28 but not sure if that's enough to fix things?

**Comment by yuvipanda** [comment]
https://github.com/cryptnono/cryptnono/pull/27 and https://github.com/cryptnono/cryptnono/pull/29 seem to have fixed it.

**Comment by GeorgianaElena** [comment]
Yaay! 🚀

**Pull request merged**
