### PR TITLE
[UCMerced to be merged Friday 9:30 AM PT] Update ucmerced prod to match staging

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Fixes https://github.com/2i2c-org/infrastructure/issues/3188

This should be merged Friday, after 9:30 AM PT.

Note that this requires somebody else to hit the merge button, because that is 7:30PM Friday for me and I won't be available :( (cc @damianavila )

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
Reminder that this needs to be merged tonight and we don't have anybody assigned.

**Review by sgibson91 — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
Thanks @sgibson91!

**Comment by damianavila** [comment]
Thanks @sgibson91 for merging on Sunday time!

**Comment by damianavila** [comment]
In the future we should push back strongly on late Friday deployments, I will make sure that is the guideline we follow.
Also thanks @GeorgianaElena for the ping (that I saw quite late 😉).

**Pull request merged**
