### PR TITLE
Enable alerting on full disk for Azure clusters

### PR DESCRIPTION
**Pull request by sgibson91**
- fixes https://github.com/2i2c-org/infrastructure/issues/3320

Unlike in GCP, we only have access to a `UsedCapacity` metric (as opposed to a percentage of free disk space). Therefore, I have tried to define a fraction of the total storage size _above which_ we trigger an alert.

### CODE REVIEW

**Comment by sgibson91** [comment]
I am having issues using `locals` to multiply a threshold fraction with the storage size variable

```
$ tf plan -var-file=projects/$CLUSTER_NAME.tfvars -out=$CLUSTER_NAME
Releasing state lock. This may take a few moments...
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 28, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   28:   name                = "Available disk space < ${locals.storage_threshold} GB on ${var.project_id}"
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 31, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   31:   description         = "Action will be triggered when available disk space is < ${locals.storage_threshold} GB."
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 38, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   38:     threshold        = "${locals.storage_threshold * 1000000000}"  # Convert GB to Bytes
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
╵
❯ tf plan -var-file=projects/$CLUSTER_NAME.tfvars -out=$CLUSTER_NAME
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 28, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   28:   name                = "Used disk space > ${locals.storage_threshold} GB on ${var.project_id}"
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 31, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   31:   description         = "Action will be triggered when used disk space is > ${locals.storage_threshold} GB."
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on pagerduty.tf line 38, in resource "azurerm_monitor_metric_alert" "disk_space_full_alert":
│   38:     threshold        = "${locals.storage_threshold * 1000000000}"  # Convert GB to Bytes
│ 
│ A managed resource "locals" "storage_threshold" has not been declared in the root module.
```

**Comment by sgibson91** [comment]
I am also unsure where to insert the integration key, we may not need sops? https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_action_group

**Comment by sgibson91** [comment]
Errors from planning 

```
$ tf plan -var-file=projects/$CLUSTER_NAME.tfvars -out=$CLUSTER_NAME
data.sops_file.pagerduty_service_integration_keys: Reading...
data.sops_file.pagerduty_service_integration_keys: Read complete after 1s [id=-]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: building client: unable to obtain access token: running Azure CLI: exit status 1: ERROR: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-12-01T16:32:40.8669647Z and was inactive for 90.00:00:00. Trace ID: cf358c5d-87c2-4998-bbef-46a087ea0d00 Correlation ID: f711107c-51e8-4eb5-b8ce-9578653e8693 Timestamp: 2024-06-11 09:27:28Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│ 
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 43, in provider "azuread":
│   43: provider "azuread" {
│ 
╵
╷
│ Error: building account: getting authenticated object ID: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-12-01T16:32:40.8669647Z and was inactive for 90.00:00:00. Trace ID: 00104319-713e-4006-9f45-82ca8d145d00 Correlation ID: c129ece2-49fa-489a-84b9-ee19af68e1e9 Timestamp: 2024-06-11 09:27:29Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com//.default
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 47, in provider "azurerm":
│   47: provider "azurerm" {
```

**Comment by sgibson91** [comment]
New set of errors

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # azurerm_monitor_action_group.alerts will be created
  + resource "azurerm_monitor_action_group" "alerts" {
      + enabled             = true
      + id                  = (known after apply)
      + name                = "AlertsActionGroup"
      + resource_group_name = "2i2c-utoronto-cluster"
      + short_name          = "alertaction"

      + webhook_receiver {
          + name        = "callpagerdutyapi"
          + service_uri = "https://events.pagerduty.com/integration/5ebdc22d2399400cd0560e450b579333/enqueue"
        }
    }

  # azurerm_monitor_metric_alert.disk_space_full_alert will be created
  + resource "azurerm_monitor_metric_alert" "disk_space_full_alert" {
      + auto_mitigate            = true
      + description              = "Action will be triggered when used disk space is > 7372.8 GB."
      + enabled                  = true
      + frequency                = "PT1M"
      + id                       = (known after apply)
      + name                     = "Used disk space > 7372.8 GB on ead3521a-d994-4a44-a68d-b16e35642d5b"
      + resource_group_name      = "2i2c-utoronto-cluster"
      + scopes                   = [
          + "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage",
        ]
      + severity                 = 3
      + target_resource_location = (known after apply)
      + target_resource_type     = (known after apply)
      + window_size              = "PT5M"

      + action {
          + action_group_id = (known after apply)
        }

      + criteria {
          + aggregation            = "Average"
          + metric_name            = "UsedCapacity"
          + metric_namespace       = "Microsoft.Storage/storageAccounts"
          + operator               = "GreaterThan"
          + skip_metric_validation = false
          + threshold              = 7372800000000
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
╷
│ Error: retrieving Cluster: (Managed Cluster Name "hub-cluster" / Resource Group "2i2c-utoronto-cluster"): containerservice.ManagedClustersClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'canadacentral' and API version '2022-01-02-preview' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01, 2020-03-01, 2020-04-01, 2020-06-01, 2020-07-01, 2020-09-01, 2020-11-01, 2020-12-01, 2021-02-01, 2021-03-01, 2021-05-01, 2021-07-01, 2021-08-01, 2021-09-01, 2021-10-01, 2022-01-01, 2022-02-01, 2022-03-01, 2022-04-01, 2022-06-01, 2022-07-01, 2022-07-02-preview, 2022-08-01, 2022-08-02-preview, 2022-08-03-preview, 2022-09-01, 2022-09-02-preview, 2022-10-02-preview, 2022-11-01, 2022-11-02-preview, 2023-01-01, 2023-01-02-preview, 2023-02-01, 2023-02-02-preview, 2023-03-01, 2023-03-02-preview, 2023-04-01, 2023-04-02-preview, 2023-05-01, 2023-05-02-preview, 2023-06-01, 2023-06-02-preview, 2023-07-01, 2023-07-02-preview, 2023-08-01, 2023-08-02-preview, 2023-09-01, 2023-09-02-preview, 2023-10-01, 2023-10-02-preview, 2023-11-01, 2023-11-02-preview, 2024-01-01, 2024-01-02-preview, 2024-02-01, 2024-02-02-preview, 2024-03-02-preview, 2024-04-02-preview'. The supported locations are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, brazilsoutheast, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2, francecentral, francesouth, germanynorth, germanywestcentral, israelcentral, italynorth, japaneast, japanwest, jioindiacentral, jioindiawest, koreacentral, koreasouth, mexicocentral, northcentralus, northeurope, norwayeast, norwaywest, polandcentral, qatarcentral, southafricanorth, southafricawest, southcentralus, southindia, southeastasia, spaincentral, swedencentral, switzerlandnorth, switzerlandwest, uaecentral, uaenorth, uksouth, ukwest, westcentralus, westeurope, westus, westus2, westus3'."
│ 
│   with azurerm_kubernetes_cluster.jupyterhub,
│   on main.tf line 82, in resource "azurerm_kubernetes_cluster" "jupyterhub":
│   82: resource "azurerm_kubernetes_cluster" "jupyterhub" {
│ 
╵
╷
│ Error: shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.\nRequestId:ede3c532-a01a-005d-3fe2-bbfe7f000000\nTime:2024-06-11T09:31:08.7272972Z"
│ 
│   with azurerm_storage_share.homes,
│   on storage.tf line 28, in resource "azurerm_storage_share" "homes":
│   28: resource "azurerm_storage_share" "homes" {
```

**Comment by sgibson91** [comment]
> │ Error: shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.\nRequestId:ede3c532-a01a-005d-3fe2-bbfe7f000000\nTime:2024-06-11T09:31:08.7272972Z"
> │ 
> │   with azurerm_storage_share.homes,
> │   on storage.tf line 28, in resource "azurerm_storage_share" "homes":
> │   28: resource "azurerm_storage_share" "homes" {

This issue is related to https://github.com/2i2c-org/infrastructure/issues/890

**Comment by GeorgianaElena** [comment]
```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # azurerm_kubernetes_cluster.jupyterhub will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "jupyterhub" {
        id                                  = "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.ContainerService/managedClusters/hub-cluster"
      + image_cleaner_enabled               = false
      + image_cleaner_interval_hours        = 48
        name                                = "hub-cluster"
        tags                                = {}
        # (29 unchanged attributes hidden)

      ~ default_node_pool {
            name                         = "core"
            tags                         = {}
            # (23 unchanged attributes hidden)

          - upgrade_settings {}
        }

        # (5 unchanged blocks hidden)
    }

  # azurerm_kubernetes_cluster_node_pool.user_pool["usere8sv5"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "user_pool" {
        id                      = "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.ContainerService/managedClusters/hub-cluster/agentPools/usere8sv5"
        name                    = "usere8sv5"
        tags                    = {}
        # (26 unchanged attributes hidden)

      - upgrade_settings {}
    }

  # azurerm_storage_account.homes will be updated in-place
  ~ resource "azurerm_storage_account" "homes" {
      ~ allow_nested_items_to_be_public   = false -> true
        id                                = "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage"
      ~ min_tls_version                   = "TLS1_0" -> "TLS1_2"
        name                              = "2i2cutorontohubstorage"
        tags                              = {}
        # (28 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│ 
│   with azurerm_kubernetes_cluster.jupyterhub,
│   on main.tf line 146, in resource "azurerm_kubernetes_cluster" "jupyterhub":
│  146:     node_taints = concat([], var.node_pools["core"][0].taints)
│ 
│ This field will be removed in v4.0 of the Azure Provider since the AKS API doesn't allow arbitrary node taints on the default node pool
╵
╷
│ Error: executing request: unexpected status 403 (403 This request is not authorized to perform this operation.) with AuthorizationFailure: This request is not authorized to perform this operation.
│ RequestId:ec51387d-101a-0058-58eb-bb2ca4000000
│ Time:2024-06-11T10:40:06.8326601Z
│ 
│   with azurerm_storage_share.homes,
│   on storage.tf line 28, in resource "azurerm_storage_share" "homes":
│   28: resource "azurerm_storage_share" "homes" {
│ 
╵

```

**Comment by sgibson91** [comment]
Plan output with a targeted command to avoid issue with NFS share

```
$ tf plan -var-file=projects/$CLUSTER_NAME.tfvars -out=$CLUSTER_NAME -target=azurerm_monitor_action_group.alerts -target=azurerm_monitor_metric_alert.disk_space_full_alert

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_monitor_action_group.alerts will be created
  + resource "azurerm_monitor_action_group" "alerts" {
      + enabled             = true
      + id                  = (known after apply)
      + location            = "global"
      + name                = "AlertsActionGroup"
      + resource_group_name = "2i2c-utoronto-cluster"
      + short_name          = "alertaction"

      + webhook_receiver {
          + name        = "callpagerdutyapi"
          + service_uri = "https://events.pagerduty.com/integration/5ebdc22d2399400cd0560e450b579333/enqueue"
        }
    }

  # azurerm_monitor_metric_alert.disk_space_full_alert will be created
  + resource "azurerm_monitor_metric_alert" "disk_space_full_alert" {
      + auto_mitigate            = true
      + description              = "Action will be triggered when used disk space is > 7372.8 GB."
      + enabled                  = true
      + frequency                = "PT1M"
      + id                       = (known after apply)
      + name                     = "Used disk space > 7372.8 GB on ead3521a-d994-4a44-a68d-b16e35642d5b"
      + resource_group_name      = "2i2c-utoronto-cluster"
      + scopes                   = [
          + "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage",
        ]
      + severity                 = 3
      + target_resource_location = (known after apply)
      + target_resource_type     = (known after apply)
      + window_size              = "PT5M"

      + action {
          + action_group_id = (known after apply)
        }

      + criteria {
          + aggregation            = "Average"
          + metric_name            = "UsedCapacity"
          + metric_namespace       = "Microsoft.Storage/storageAccounts"
          + operator               = "GreaterThan"
          + skip_metric_validation = false
          + threshold              = 7372800000000
        }
    }

  # azurerm_storage_account.homes will be updated in-place
  ~ resource "azurerm_storage_account" "homes" {
      ~ allow_nested_items_to_be_public   = false -> true
        id                                = "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage"
      ~ min_tls_version                   = "TLS1_0" -> "TLS1_2"
        name                              = "2i2cutorontohubstorage"
        tags                              = {}
        # (28 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 2 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to
│ use it as part of an error message.
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_container_registry.container_registry" from prior state: unsupported attribute "georeplication_locations"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_kubernetes_cluster.jupyterhub" from prior state: unsupported attribute "addon_profile"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_kubernetes_cluster_node_pool.user_pool[\"usere8sv5\"]" from prior state: unsupported attribute "availability_zones"
╵
```

**Comment by sgibson91** [comment]
This has been applied and successfully triggered alerts to pagerduty slack channel

**Pull request merged**
